### ISSUE TITLE
Suche und Filter kombinieren

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-cytoscape.js#120]
Es wäre schön, wenn bei eingeschalteten Filtern die Resultate aus den gewählten Subontologien extra angezeigt werden (bsp.weise oben). Außerdem wäre eine farbliche Markierung, wie im Graph, bei den Suchergebnissen wünschenswert.

*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:

**Comment by KonradHoeffner** [comment]
Momentan funktioniert die Suche nur auf dem SPARQL Endpunkt und zieht bei der Anzeige der Ergebnisliste überhaupt nicht in Betracht, ob ein Ergebnis im Graph ist oder nicht.

- [ ] Für jedes Ergebnis prüfen, ob es im Graph ist (Node suchen mit Attribut NODE.ID = URI des Ergebnisses).
- [ ] Für jedes Ergebnis im Graph prüfen, ob es im Filter angezeigt wird.
- [ ] Drei unterschiedliche Farben für: Nicht im Graph, im Graph aber ausgefiltert, im Graph und "eingefiltert".
