### ISSUE TITLE
Circle Star

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#123]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:

Beim Circle Star werden zu einem ausgewählten Begriff die damit unmittelbar per CloseMatch verbundenen Begriffe in die Mitte gestellt. Z.B. bei http://www.snik.eu/ontology/bb/StrategicInformationManagementPlan gibt es aber einen Begriff, der dazu in CloseMatch-Beziehung steht, z.B. http://www.snik.eu/ontology/ciox/ITStrategie, und dieser hat wieder eine  CloseMatch-Beziehung, hier zu http://www.snik.eu/ontology/he/ItStrategie. Ich hätte gerne alle close matches in der Mitte vom Circle Star, auch wenn sie über n close matches mit dem Start-Begriff zusammenhängen. 
AW

**Comment by AlfredWinter** [comment]
Ich komme mit den Issue-Trackern durcheinander. Habe gerade eben noch etwas zum CircleStar eingetragen, wo ich dieses hier (#123) nicht mehr finden konnte. Jetzt finde ich das von vor 5 Minuten nicht mehr. Sorry. Beides hängt zusammen.

**Comment by AlfredWinter** [comment]
Gerade bin ich wieder auf dieses Thema gestoßen. Wenn der Begriff, zu dem ich 'closeStar' mache, mehrer closemathes zu anderen Begriffen hat, wird nur einer in die Mitte gestellt und dazu auch die umliegenden Begriffe angezeigt. Z.B. bei http://www.snik.eu/ontology/ob/ProjectPortfolio wird zwar der closematch zu http://www.snik.eu/ontology/he/Projektportfolio berücksichtigt, nicht aber der closematch zu http://www.snik.eu/ontology/bb/ProjectPortfolio.
AW

**Comment by AlfredWinter** [comment]
Bin gerade wieder drauf gestoßen. Für wann ungefähr ist der milestone eingeplant?
AW

**Comment by KonradHoeffner** [comment]
Den transitiven CloseMatch in der Mitte haben wir heute eingebaut. Bei der Sortierung gibt es noch Probleme aber wir arbeiten daran.

**Comment by KonradHoeffner** [comment]
Sortierung ist jetzt drin, auch wenn sie noch vereinzelt Vertauschungen enthalten kann, aber das zu perfektionieren wäre sehr aufwendig wenn überhaupt möglich.
