### ISSUE TITLE
Create a SNIK thesaurus

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#125]
- synonyms (matches) and other related classes
- page number

**Comment by KonradHoeffner** [comment]
What would be the difference to LodLive?

**Comment by FranziskaJahn** [comment]
Ich weiß nicht, was es damit auf sich hat und wo das herkommt?!

**Comment by KonradHoeffner** [comment]
Ich weiß leider auch nicht mehr, wer das in Auftrag gegeben hat, ich dachte du wärst das gewesen.

**Comment by KonradHoeffner** [comment]
Discuss in next meeting.

**Comment by AlfredWinter** [comment]
Close because unclear who wants it.
