### ISSUE TITLE
snik.eu/graph wird nicht angezeigt auf iPad

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-cytoscape.js#141]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser: Safari auf iPad mit iOS 12.1

Wenn man die Webseite snik.eu/graph aufruft, wird die Menüliste geladen und der Ladezeit-"Spinner" wird angezeigt. Allerdings wird der Graph nach Ablauf des Spinners nicht angezeigt.

**Comment by KonradHoeffner** [comment]
- [ ] iPad mitbringen
- [ ] Fehler identifizieren
- [ ] Fehler beheben
- [ ] Benutzbarkeit der GUI-Elemente mit iPad sicherstellen, z.B. das Kontextmenü

**Comment by AnnaLoerke** [comment]
[Warning] Total canvas memory use exceeds the maximum limit (576 MB). (cytoscape.min.js, line 10)
[Log] Layout not in cache, recalculating layout... – "            [main.bundle.js:1961:51]" (main.bundle.js, line 2357)
[Error] TypeError: null is not an object (evaluating 'm.context.setTransform')
	getElement (cytoscape.min.js:10:143902)
	drawCachedElement (cytoscape.min.js:10:154342)
	drawCachedElements (cytoscape.min.js:10:154650)
	drawLayeredElements (cytoscape.min.js:10:155008)
	render (cytoscape.min.js:10:174766)
	t (cytoscape.min.js:10:138776)

**Comment by KonradHoeffner** [comment]
Das Problem tritt nur auf dem iPad mit Safari 12 auf, nicht auf dem MacBook Pro mit Safari 12.

Ein Workaround ist, nur das blaue Buch zu laden. Mit dem blauen und orangen geht es sporadisch.

**navigator.userAgent**
String mit iPad mit iOS12: Mozilla/5.0 (iPad; CPU OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0 Mobile/15E148 Safari/604.1

String mit MacBook Pro mit macOS Mojave V10.14.1 und Safari 12.0.1: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_1) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.1 Safari/605.1.15

**Comment by KonradHoeffner** [comment]
Da es ein Fehler des neuen Safaris zu sein scheint, schlage ich vor, erstmal zu warten, ob das behoben wird, ich verschiebe es daher in den "next"-Meilenstein.
Parallel dazu laden wir im pgraph jetzt nur noch das blaue und orange Buch, eine andere Lösungsmöglichkeit ist uns jetzt nicht bekannt, da es in der Cytoscape.js Bibliothek vorkommt.
Es scheint aber auch vom caching abzuhängen.

**Comment by KonradHoeffner** [comment]
Update 15.1.2019: Es scheint sich noch nichts getan zu haben beim Safari.

**Comment by KonradHoeffner** [comment]
Wait for the next Safari (Safari 13?) and test again.

**Comment by ThomasPause** [comment]
tested again today on my ipad pro (2017), runs super on both firefox and safari.
contextmenu is shown by clicking with two fingers  
done, close.
