### ISSUE TITLE
Zoom auf Laptop

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#142]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Wie kann ich auf meinem Laptop, wenn ich kein Mausrad habe, hinein und hinaus zoomen? Ggf. ist ein Menüpunkt nötig oder eine enstspr. Hilfe
AW

**Comment by KonradHoeffner** [comment]
Geht es auf dem Trackpad mit zwei Fingern?

**Comment by AlfredWinter** [comment]
Ja, geht!
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Montag, 3. Dezember 2018 15:37
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Zoom auf Laptop (#142)
 
Geht es auf dem Trackpad mit zwei Fingern?

**Comment by KonradHoeffner** [comment]
Wunderbar! Reicht das dann an Zoomfunktionalität aus oder soll noch etwas hinzugefügt werden, z.B. eine Skala wie bei Google Maps?

**Comment by AlfredWinter** [comment]
Eine googlemapsartige Skala fände ich gut.
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Montag, 3. Dezember 2018 16:20
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Zoom auf Laptop (#142)
 
Wunderbar! Reicht das dann an Zoomfunktionalität aus oder soll noch etwas hinzugefügt werden, z.B. eine Skala wie bei Google Maps?

**Comment by KonradHoeffner** [comment]
TODO: Integrate https://github.com/cytoscape/cytoscape.js-panzoom

**Comment by KonradHoeffner** [comment]
Panzoom funktioniert, allerdings braucht es jQuery. Dadurch werden 70kb mehr Platz verbraucht und die Startzeit steigt um 74 ms. Ist das akzeptabel?

**Comment by AlfredWinter** [comment]
Ich finde ja.

**Comment by KonradHoeffner** [comment]
OK, dann baue ich es ein.

**Comment by KonradHoeffner** [comment]
OK, ist eingebaut. @T-P-1: Falls du eine Möglichkeit ohne jQuery und FontAwesome kennst, wäre das besser, da es dann schneller laden würde, aber es funktioniert erst mal so.

**Comment by T-P-1** [comment]
top, ich schau mal, ob mir noch was anderes einfaellt
