### ISSUE TITLE
Layout von SNIK-graph

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#144]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Lieber herr Höffner, 
seit einiger Zeit startet SNIK.eu/graph mit einem neuen Layout der Galaxie. Es ist jetzt eher eine Kugel. Das alte Layout fand ich besser: da waren die Teilonotologien getrennt und die Knoten waren nicht so dicht gepackt. Nun kann selbst beim Hineinzoomen nichts mehr erkennen, da sich Knoten-Silhouetten und die Beschreibungen stark überlagern.
Gruß, AW

**Comment by T-P-1** [comment]
Lieber Herr Winter,
wir haben eine neue Funktion implementiert um die Teilontologien separat anzeigen zu können. Diese lässt sich über die ´options´ durch aktivieren von ´seperate subontologies´ nutzen (Anschließend bitte das Layout neu berechnen lassen!). 
Die geänderte Darstellung des gesamten Graphen resultiert aus der dafür nötigen Änderung der Gravitationsverhältnisse. 
Löst das Ihre Anfrage oder sollen wir noch einmal anders in dieser Sache tätig werden?
Beste Grüße, Konrad Höffner und Thomas Pause

**Comment by AlfredWinter** [comment]
Lieber Herr Pause, ja, das löst das Problem. Schön.  Aber noch etwas: Wo ist die „Hide“ –Funktion im Kontextmenü geblieben?
Grüße, AW
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Thomas Pause [mailto:notifications@github.com] 
Gesendet: Freitag, 7. Dezember 2018 14:07
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Layout von SNIK-graph (#144)
 
Lieber Herr Winter,
wir haben eine neue Funktion implementiert um die Teilontologien separat anzeigen zu können. Diese lässt sich über die ´options´ durch aktivieren von ´seperate subontologies´ nutzen (Anschließend bitte das Layout neu berechnen lassen!).
Die geänderte Darstellung des gesamten Graphen resultiert aus der dafür nötigen Änderung der Gravitationsverhältnisse.
Löst das Ihre Anfrage oder sollen wir noch einmal anders in dieser Sache tätig werden?
Beste Grüße, Konrad Höffner und Thomas Pause

**Comment by KonradHoeffner** [comment]
Die hide Funktion wurde in "remove" umbenannt, um deutlich zu machen, dass die Elemente bei "reset style" nicht wiederkommen sondern nur nach einen Neuladen.
