### ISSUE TITLE
 "TypeError: NetworkError when attempting to fetch resource" => Source Map URL: browser-polyfill.js.map

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#147]
Opening index-dev.html in firefox-developer-edition 64.0b14 (64-bit) on Arch Linux results in the following console warning:

```
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: moz-extension://ebc90d47-a515-442a-968d-4d2d1b8ef7a0/lib/browser-polyfill.min.js
Source Map URL: browser-polyfill.min.js.map[Learn More] 
```
I don't know where this comes from as index-dev.html does not load any polyfills directly. Maybe this comes from some dependency?

**Comment by donni106** [comment]
Have you checked your Firefox extensions? `moz-extension` triggers this thought. Deactivate extensions and try it again.

**Comment by T-P-1** [comment]
does not occur anymore, @donni106 seems to be right.
