### ISSUE TITLE
refactor the panzoom element

### ISSUE THREAD

**Issue by T-P-1** [IMISE/snik-cytoscape.js#149]
for now, it is in the left upper corner where it blocks the menu (esp. File) and the search results. I suggest to put it in a lower right position where it does not block anything. Alternatively, we should shift the whole menu a little bit to the right and put the panzoom into its own container on the left, so it can keep its actual position.

**Comment by FranziskaJahn** [comment]
Gerade wollte ich darüber meckern, aber ihr habt es ja selbst schon erkannt ;-)
Bin auch für unten rechts.

**Comment by T-P-1** [comment]
done.
