### ISSUE TITLE
Search problems 

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-cytoscape.js#163]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser: Firefox 64 on macOS

Ich habe erneut Probleme mit der Suche; Beispiel: Ich suche "DurchfuehrungJourFixeCEO" (so heißt die Klasse als Endung) und er findet nichts. Gleiches gilt bei Leerzeichen zwischen den Wörtern oder wenn ich ue durch ü ersetze. Suche ich dann nur CEO wird mir die Klasse als eine mögliche zur Auswahl angezeigt.

**Comment by AnnaLoerke** [comment]
Kann das Problem eventuell darin bestehen, dass in den Labels jeweils ein - zwischen Jour und Fixe steht? Vielleicht bekommen wir es hin, dass er das sowohl mit, als auch ohne - akzeptiert? Das Problem wird es ja bei anderen Begriffen auch geben.

**Comment by KonradHoeffner** [comment]
Habe das jetzt behoben in commit a9d7565b38a13c17f9168cedb12faea6a164aa63 aber wenn noch mehr Funktionalität in die Suche soll, macht es mehr Sinn eine professionelle Suchbibliothek zu benutzen wie zum Beispiel lunr.js. Wenn gewünscht, kann ich das gerne einbauen, kann aber ein paar Stunden dauern.

**Comment by AlfredWinter** [comment]
FJ: Anschauen im Hinblick auf HITO.
AL: 3LGM2 soll 3LGM² finden.

Beschluss: Suchbibliothek einbauen.

**Comment by KonradHoeffner** [comment]
Ich sehe da zwei Kandidaten: Fuse.js und Lunr.js. Mit Fuse.js habe ich Erfahrung und es ist sehr einfach zu benutzen.

**Comment by KonradHoeffner** [comment]
Ich kann Beispiele für Suchanfragen die nicht funktionieren gut gebrauchen als Testfall für die neue Suche, bitte hier reinschreiben.

**Comment by KonradHoeffner** [comment]
Die Suche ist jetzt drin, gibt aber noch etwas zu viel zurück, ich arbeite daran.
Sie ist auch ein bisschen langsamer als die alte, da erst ein Volltextindex erstellt werden muss. Ich kann diesen auch cachen, aber dann wäre er nicht immer aktuell. Was ist für die Benutzer wichtiger?

**Comment by KonradHoeffner** [comment]
Things in search results but not in the graph should be opened in lodview instead of just giving a warning.

**Comment by KonradHoeffner** [comment]
Ist jetzt im pgraph zum testen online, ich glaube das leerzeichen insensitive ist aber nicht gut weil es dann z.B. "CEO" in "Maintenance of" findet.

**Comment by AlfredWinter** [comment]
Danke. Ich habe es getestet, aber komische Ergebnisse:

- suchen nach "projektleiter" und "projekt leiter" führen zum selben Ergebnis. Auch der "projectmanager" wird gefunden.

- Suche nach "projektmanager" führt nur zu einem projektmanager, nicht aber zu den Projektleitern.

**Comment by KonradHoeffner** [comment]
Der ob:ProjectManager wird gefunden, weil er als deutsches Label "Projektleiter" hat, das ist damit eine exakte Übereinstimmung und funktioniert also wie geplant.

"projekt leiter" findet eine Obermenge von "projektleiter",da "projekt leiter" tokenisiert wird in ["projekt","leiter"] und jedes Token separat gematcht wird. Daher findet "projekt leiter" 38 Klassen aber "projektleiter" nur "33".

Bei einer Suche nach "projektmanager" kann man he:Projektleiter nicht finden, da dieser nur das deutsche Label "Projektleiter" hat. Eine Möglichkeit wäre, für solche Sachen close matches in die Suche zu integrieren aber das wäre zusätzlicher Aufwand und würde die Suche um einiges verlangsamen, außerdem gibt es ja dafür die Visualisierung. Ich kann es aber trotzdem mit einbauen.

ciox:Projektleiter findet er nicht, weil das Label "Project Manager" ist und daher in zwei Tokens zerlegt wird. Mit einer Suche nach "project manager" oder "projekt manager" findet man es aber.

**Comment by KonradHoeffner** [comment]
**Related commits**:

ca2f67052b2e1df76450ba59c0dc2f6353eb5db4, 6c084cef3d06b467cddc98147d1fec5c536563d2, 2d9276c7478dccf04636ef5aa6ee24e7cbcceab3, 97ec16f41838e63a0fca7683836d3c90c38ce612, 4c2c9a111a3ff7a396b63ec6c2bcf6f497ee7fa4, 179b40f483b2535f1d1965d701536f8cf25093c8, 6e376584b9c82285fbf59cd98c99a326e6972b07, d19f4e8c1ffee21092267cf0214ba1165dfe0737, 35d7f71240866843546911e47ac041c8a005a3b0, 4d85c95bd0ac0a0b9ec1b631d7855ef0c67e400b, ef0dff5020bbfc12ad7831f087334b36fc87034c, 11352fdf28049b6628c0de95b384a87e70e4378d
