### ISSUE TITLE
Load graph from menu does not work

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#166]

**Comment by AlfredWinter** [comment]
Ich brauche für meinen China-Vortrag dringend die Funktionen zum download der hochauflösenden Bilder - insbesondere whole graph, damit ich mit Vergrößerungen darin rumfahren kann. Bitte mit hoher Priorität bearbeiten. AW @KonradHoeffner @ThomasPause

**Comment by KonradHoeffner** [comment]
- [ ] load graph with layout
- [ ] load layout
- [ ] load from SPARQL endpoint

- [ ]

**Comment by KonradHoeffner** [comment]
Alle Ladeoperationen funktionieren jetzt wieder.

**Comment by AlfredWinter** [comment]
Nee, bei mir nicht. Ich habe den Cache gelöscht.

**Comment by KonradHoeffner** [comment]
Mein Fehler, ich hatte vergessen, es auf dem Server zu aktualisieren. Geht es jetzt?
