### ISSUE TITLE
Variable Spring Length

### ISSUE THREAD

**Issue by BirgitSNIK** [IMISE/snik-cytoscape.js#170]
Bitte Spring Length (Abstand der Knoten) variabel gestalten, in Abhängigkeit von der Anzahl der visualisierten Knoten. Zunächst als Menüpunkt für Birgit, damit sie ausprobieren kann, welche Längen bei wievielen Knoten geeignet sind.

**Comment by KonradHoeffner** [comment]
Nachdem ich jetzt ewig versucht habe, das abhängig von der Knotenzahl zu machen, was wegen der Struktur des Programms schlecht ging, habe ich dir jetzt einfach einen zweiten Knopf eingebaut :-) Er heißt "tight layout" und zieht das ganze etwas enger zusammen.

**Comment by BirgitSNIK** [comment]
Danke, ich werde es nächste Woche ausprobieren.
Birgit


Am 13.02.2019 17:07 schrieb Konrad Höffner <notifications@github.com>:
Nachdem ich jetzt ewig versucht habe, das abhängig von der Knotenzahl zu machen, was wegen der Struktur des Programms schlecht ging, habe ich dir jetzt einfach einen zweiten Knopf eingebaut :-) Er heißt "tight layout" und zieht das ganze etwas enger zusammen.

**Comment by KonradHoeffner** [comment]
Nachdem ich jetzt ewig versucht habe, das abhängig von der Knotenzahl zu machen, was wegen der Struktur des Programms schlecht ging, habe ich dir jetzt einfach einen zweiten Knopf eingebaut :-) Er heißt "tight layout" und zieht das ganze etwas enger zusammen.

**Comment by KonradHoeffner** [comment]
Es gibt jetzt auch ein "custom layout" mit einem Schieberegler.

**Comment by BirgitSNIK** [comment]
Hi Konrad,
bei mir sieht es auf dem Bildschirm gerade aus wie an Silvester am Himmel: Wunderschöne Sternchenraketen!
Hab zwar noch nicht ganz kapiert, was ich wie und wann mit meinen Spezialknöpfen machen kann, aber ich denke, die tun ziemlich genau das, was ich will. Ich muss nur noch etwas üben J!
Vielen Dank für diese Knöpfe!
 
Von: Konrad Höffner <notifications@github.com> 
Gesendet: Donnerstag, 14. Februar 2019 10:22
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Variable Spring Length (#170)
 
Es gibt jetzt auch ein "custom layout" mit einem Schieberegler.
