### ISSUE TITLE
sorry, neuer fork

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#173]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Sorry, ich habe versehentlich einen neuen Fork creiert. Bitte wieder löschen, falls das geht. AW

**Comment by KonradHoeffner** [comment]
Löschen wurde vor kurzem zu Git hinzugefügt aber ich habe die Rechte dafür nicht, ich schließe es daher einfach.
