### ISSUE TITLE
shortest Path

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#174]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Wie aktiviert man einen kürzesten Pfad, wenn die beiden zu verbindenden Knoten nicht gerade direkt nebeneinander liegen, sondern mit der Suche erst gesucht werden müssen??
AW

**Comment by KonradHoeffner** [comment]
1. Rechtsklick auf den Startknoten, es erscheint das Kontextmenü. Dann können Sie dort "set as path source" auswählen.
2. Jetzt können Sie suchen und auf den Zielknoten rechtsklicken. Im Kontextmenü können Sie jetzt "path" auswählen und der kürzeste Weg wird von dem Startknoten aus gefunden.

**Comment by KonradHoeffner** [comment]
Funktioniert es so?

**Comment by KonradHoeffner** [comment]
Ich schließe die Issue. Falls das Problem wieder auftreten sollte, bitte wieder öffnen.

**Comment by AlfredWinter** [comment]
Ja funktionierte. Ist o.k.

**Comment by AlfredWinter** [comment]
Aber ich fürchte, das wieder zu vergessen. Auch für andere Nutzer ist das nicht sofort einsichtig. Ist das im Help beschrieben?

**Comment by KonradHoeffner** [comment]
Hm das steht tatsächlich weder im Manual noch im Tutorial.

@ThomasPause: Kannst du mal das Manual aktualisieren und gleich noch die Hilfemenüeinträge auf Deutsch übersetzen.

**Comment by KonradHoeffner** [comment]
Planänderung: Hilfemenü nicht übersetzen, da die dahinter liegenden Seiten auf Englisch sind, das könnte verwirren.
