### ISSUE TITLE
save image

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#175]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Die Funktionen zur Erzeugung eines Image funktionieren nicht. Gerade hochaufgelöste Bilder brauche ich für meinen China-Vortrag

**Comment by AlfredWinter** [comment]
@KonradHoeffner : ist ziemlich dringend. Bitte kurzes Feedback, ob das kurzfristig lösbar ist, oder ob ich mich  mit Screenshots behelfen soll. AW

**Comment by KonradHoeffner** [comment]
Ich kümmere mich sofort darum!

**Comment by KonradHoeffner** [comment]
Funktioniert wieder.

**Comment by AlfredWinter** [comment]
lassen sich auch "Load" functionen, insbesondere Load Layout, wiederherstellen?
