### ISSUE TITLE
Kontextmenü

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#176]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Das Kontextmenü ist nicht erwartungskonform. 
Üblicherweise erscheint das Kontextmenü mit einem einfachen rechtsclick und bleibt auch stehen. So sollte es hier auch sein.

Das Öffnen des Kontextmenüs durch langen linksclick führt zu Problemen bei schlechter Performance: Wenn man einen Knoten bewegen will und er reagiert nicht sofort und man hält die clicktaste daher gedrückt, öffnet sich das Kontextmenü und man kann den knoten nicht bewegen. Das Kontextmenü sollte nicht mehr mit langem Linksclick geöffnet werden können. 
Wenn man einen Knoten mit rechtsclick anklickt, muss vor dem öffnen des Kontextmenüs der Knoten auch als markiert gelten. Sonst bleibt z.B. die Auswahl von "set as path source" unwirksam. 
Gruß, AW

**Comment by KonradHoeffner** [comment]
Habe den langen Klick für das Kontextmenü rausgenommen. Wer SNIK Graph auf einem Laptop oder anderem alternativen Eingabegerät benutzt, bitte Bescheid sagen, ob es damit noch geht.

**Comment by KonradHoeffner** [comment]
Ich bin nicht sicher, was die Aufgabe bei dem "set as path source" ist. Soll das nur noch durchgeführt werden, wenn der Knoten selektiert ist und sonst eine Fehlermeldung liefern?
