### ISSUE TITLE
Suche

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#178]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:

**Comment by AlfredWinter** [comment]
Könnte man bei der Suche in der Liste auch die zu einem gefundenen Begriff mit closeMatch verbundenen Begriffe anzeigen? Oder wird dann die Liste zu lang?

**Comment by KonradHoeffner** [comment]
Das habe ich auch schon überlegt, allerdings:

> [...] Eine Möglichkeit wäre, für solche Sachen close matches in die Suche zu integrieren aber das wäre zusätzlicher Aufwand und würde die Suche um einiges verlangsamen, außerdem gibt es ja dafür die Visualisierung. Ich kann es aber trotzdem mit einbauen. [...] 

(Issue https://github.com/IMISE/snik-cytoscape.js/issues/163)

Es wäre daher so langsam, da der Prozess momentan so aussieht:

1. Anfrage an Index stellen
2. Resultate vom Index darstellen

Mit closeMatches wäre es so:

1. Anfrage an Index stellen
2. Für jedes Resultat: close matches per SPARQL Query abfragen
3. Resultate mit close matches darstellen

Es kann bei der Suche mehrere hundert Treffer geben, dabei würden dann auch mehrere hundert SPARQL queries nötig werden. So eine Suche kann jetzt schon mehrere Sekunden dauern, man müsste dann eventuell länger als 10 Sekunden warten.

Eine bessere Möglichkeit wäre vielleicht, einen closeMatch cache einzurichten, oder das in den index mit einzubauen.

**Comment by KonradHoeffner** [comment]
Ich probiere es mal aus, in den Index zu integrieren. Momentan dauert das ca. 500 ms und der Suchtest ca. 6000 ms.

**Comment by KonradHoeffner** [comment]
Ich habe es jetzt andersherum gelöst: Und zwar bekommt jetzt jeder Indexeintrag einer Klasse die Labels der close matches hinzugefügt. Dadurch wird die Gewichtung der Matches nicht durcheinander gebracht, es müssen keine Duplikate gesucht werden, die Reihenfolge muss nicht angepasst werden und und es können weiterhin Arrays von URIs zurückgegeben werden anstelle von Arrays von Objekten, die dann wieder konvertiert werden müssen.

Die Zeit (microbenchmarks sind immer ungenau) ist jetzt ~ 550 ms für die Indexerstellung und ~ 6200 ms für den Suchtest (mehrere Suchabfragen).

**Comment by KonradHoeffner** [comment]
Es gibt dafür jetzt einen Konfigurationsparameter config.js#searchCloseMatch (boolean).

**Comment by KonradHoeffner** [comment]
OK, die close matches sind jetzt drin.
