### ISSUE TITLE
Ergänzung zu #175

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#179]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
lassen sich auch "Load" functionen, insbesondere Load Layout, wiederherstellen?

**Comment by KonradHoeffner** [comment]
Meinen Sie das Beheben der Bugs im File Menü? Daran arbeite ich gerade, siehe #166.

**Comment by AlfredWinter** [comment]
ja. genau.
