### ISSUE TITLE
closeMatch-Verbindung auch "removebar" machen

### ISSUE THREAD

**Issue by AnnaLoerke** [IMISE/snik-cytoscape.js#186]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:

Aktuell kann man alle Relationen auch im "normalen" Modus mit "report as incorrect" und "remove" bearbeiten. Bei closeMatch geht das nicht. Ich denke auch dort wäre "report as incorrect" und "remove" sinnvoll. Eventuell könnte man auch "confirm limes link" in die nicht developer Version übernehmen, um möglichst viel Partizipation dabei zu erhalten.

**Comment by ThomasPause** [comment]
hier wäre es sinnvoll mal drüber zu reden was nun wo hinkommt, um einen gemeinsamen Weg zu finden.

**Comment by AlfredWinter** [comment]
- remove for interlinks already fixed (see pgraph)
- Add "undo hide"  or "show hidden"

**Comment by KonradHoeffner** [comment]
Renamed in c665bb520826b277b2b2f5addbaf97f0c28eea18. Other tasks already done.
