### ISSUE TITLE
Darstellung von Begriffen, die mit closematch verbunden sind

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#200]
Ich möchte im graph solche Begriffe, die durch closematch verbunden sind in irgendeiner Weise nahe beieinander stehen haben. Denkbar wäre auch ein besonderes Symbol einzuführen, dass für alle mit close-match verbundenen Begriffe steht, und das bei Bedarf auf- und zugeklappt werden kann (wei bei 3lgm² mit Teilaufgaben). Das hätte natürlich (lästige) Auswirkungen auf alle Operatoren in der Graph-Visualisierung. 
Bitte sprechen Sie mich an, um das näher zu besprechen.

**Comment by KonradHoeffner** [comment]
Dafür gibt es glücklicherweise ["compound nodes" in Cytoscape.js](http://js.cytoscape.org/#notation/compound-nodes). Ich baue das ein und sage Bescheid wenn es fertig ist, dann können wir die Details besprechen.

**Comment by AlfredWinter** [comment]
:-) So sehr ich mich freue - Vielleicht doch erst mal mit FJ, BS, TP, AL kurz drüber reden? Es war ja eine ziemlich spontane Idee von mir...

**Comment by KonradHoeffner** [comment]
Das könnte eine große Schwachstelle von SNIK beheben, nämlich dass unterschiedliche Wissensquellen nebeneinander liegen und daher nicht verglichen werden können.

FJ und BS wären für eine Funktion zum automatischen Sichtbarmachen aller close matches von derzeit sichtbaren Elementen. Für die compound nodes können sie sich nicht erwärmen.

**Comment by AlfredWinter** [comment]
Hm. Dann sollten wir mal zusammen darüber diskutieren und dabei Beispiel-Bilder für die jeweiligen Lösungen vor uns liegen haben.

**Comment by KonradHoeffner** [comment]
Das automatische Hinzufügen von close matches kann jetzt im http://www.snik.eu/pgraph über Menü->Operations->Show Close Matches im Sternmodus getestet werden.

**Comment by AlfredWinter** [comment]
habe ich mir angesehen, macht mich aber nicht richtig glücklich. Ich glaube, ich bin ein compound-fan.

**Comment by KonradHoeffner** [comment]
So sieht ein Stern mit Show Close Matches aus:
![snik-graph-show-close-match](https://user-images.githubusercontent.com/839577/56362322-d5938580-61e9-11e9-9936-8f25aea93cc1.png)

**Comment by KonradHoeffner** [comment]
Ein Prototyp von der "Kistenvariante":
![Bildschirmfoto von 2019-04-18 16-09-28](https://user-images.githubusercontent.com/839577/56366907-725b2080-61f4-11e9-9886-aee76d96fc5e.png)

Das Layout bezieht die aber noch nicht richtig ein, das musste ich manuell zurechtschieben.

**Comment by AlfredWinter** [comment]
Ja. 
Ich finde aber, man muss die Innereien gar nicht sehen. und die abgehenden Kanten sollten an der "Kiste" andocken. Zur Form: Vielleicht genau dasselbe Symbol wie enthaltenen Begriffe aber mit einem doppelten Rand. Lassen Sie sich das mal bei 3LGM² zeigen. 
Ich habe nur noch keine Lösung für das Label, da die ja unterschiedlich sein können. Vielleicht alle untereinander?

**Comment by KonradHoeffner** [comment]
Die Kisten können leider nur rechteckig sein bei Cytoscape.js. Ich gucke mir das bei 3LGM² an.
Bei den Labels könnte man vielleicht jedes nur einmal schreiben unten drunter? Also z.B. CIO,CIO, Chief... -> CIO, Chief... .

**Comment by AlfredWinter** [comment]
das besprechen wir dann besser mündlich. Frohe Ostern!

**Comment by KonradHoeffner** [comment]
Ja ich denke auch, das ist komplizierter als ich gedacht hatte. Ich wünschen Ihnen auch frohe Ostern!

**Comment by KonradHoeffner** [comment]
Ich habe jetzt noch mal nachgesehen, warum die Erkennung der Zusammenhangskomponenten überhaupt performant global funktioniert und es liegt daran, dass der SPARQL Endpunkt gar nicht benutzt wird sondern eine Bibliotheksfunktion von Cytoscape.js, die die Zusammenhangskomponenten effizient anhand des im Speicher liegenden Graphens berechnet.

**Comment by KonradHoeffner** [comment]
# Protokoll Meeting 2019-04-24 AW AL KH

## Aufgaben
- [ ] Oberknoten bekommt ein Label der Unterknoten über Prioritätsliste bb > ob > he > it4it > ciox
- [ ] Kistenfarbe 50 % grau (immun gegen Invertierung) oder violett
- [ ] Option alle zu öffnen oder zu schließen (ist im Menü)

**Comment by AnnaLoerke** [comment]
Ergänzung: Global (im Optionsmenü) kann die Zusammenfassung für alle closeMatch ein- bzw. ausgeschaltet werden. Zusätzlich kann im Kontextmenü eines jeden Knotens diese Funktion für den Knoten und seine closeMatches ein-/ausgeschaltet werden.

**Comment by AlfredWinter** [comment]
Kistenfarbe grau: ist überholt durch farblos mit dickem Rand!
Kontextmenü der Kiste: NICHT normal wie bei einem Knoten! nur "Alle enthaltenen Knoten auf aktuellen Punkt zusammenlegen" . Auch keine Formanpassung! auch nicht die Kiste als Knoten zählen. Alles nicht nötig

**Comment by KonradHoeffner** [comment]
Aktualisierte Aufgaben

- [ ] Oberknoten bekommt ein Label der Unterknoten über Prioritätsliste bb > ob > he > it4it > ciox
- [ ] Kistenfarbe farblos mit dickem Rand zum Verschieben
- [ ] Priorisierung der z-Achse der Komponenten für Eingabe wichtig, Relationen nach hinten, damit Kiste greifbar ist, entfällt eventuell durch Rand
- [ ] Kiste Kontextmenü: "Alle enthaltenen Knoten auf aktuellen Punkt zusammenlegen"
- [ ] Hilfsknoten entfernen wenn Kiste geöffnet wird
- [ ] Label der Kisten oben drüber oder dran
