### ISSUE TITLE
tight layout hängt sich auf

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#203]
siehe Titel.

Warum steht jetzt immer dieses Zeug in den issues (siehe unten)?

Menu added
Disabled DevMode. Register Context Menu
graph-init
filter entries added
fileLoadEntries added
search field added
buttons added
select ?c
  group_concat(distinct(concat(?l,"@",lang(?l)));separator="|") as ?l
  sample(?st) as ?st
  ?src
  sample(?inst) as ?inst
  from <http://www.snik.eu/ontology/limes-exact>
from <http://www.snik.eu/ontology/match>
from <http://www.snik.eu/ontology/persian>
from <http://www.snik.eu/ontology/meta>
from <http://www.snik.eu/ontology/bb>
from <http://www.snik.eu/ontology/ob>
from <http://www.snik.eu/ontology/ciox>
from <http://www.snik.eu/ontology/he>
from <http://www.snik.eu/ontology/it4it>
  {
    ?c a owl:Class.

    OPTIONAL {?src ov:defines ?c.}
    OPTIONAL {?c meta:subTopClass ?st.}
    OPTIONAL {?c rdfs:label ?l.}
    OPTIONAL {?inst a ?c.}
  }
https://www.snik.eu/sparql?query=select%20%3Fc%0A%20%20group_concat(distinct(concat(%3Fl%2C%22%40%22%2Clang(%3Fl)))%3Bseparator%3D%22%7C%22)%20as%20%3Fl%0A%20%20sample(%3Fst)%20as%20%3Fst%0A%20%20%3Fsrc%0A%20%20sample(%3Finst)%20as%20%3Finst%0A%20%20from%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Flimes-exact%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fmatch%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fpersian%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fmeta%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fbb%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fob%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fciox%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fhe%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fit4it%3E%0A%20%20%7B%0A%20%20%20%20%3Fc%20a%20owl%3AClass.%0A%0A%20%20%20%20OPTIONAL%20%7B%3Fsrc%20ov%3Adefines%20%3Fc.%7D%0A%20%20%20%20OPTIONAL%20%7B%3Fc%20meta%3AsubTopClass%20%3Fst.%7D%0A%20%20%20%20OPTIONAL%20%7B%3Fc%20rdfs%3Alabel%20%3Fl.%7D%0A%20%20%20%20OPTIONAL%20%7B%3Finst%20a%20%3Fc.%7D%0A%20%20%7D&format=json
sparql-classes
select  ?c ?p ?d ?g
  from <http://www.snik.eu/ontology/limes-exact>
from <http://www.snik.eu/ontology/match>
from <http://www.snik.eu/ontology/persian>
from <http://www.snik.eu/ontology/meta>
from <http://www.snik.eu/ontology/bb>
from <http://www.snik.eu/ontology/ob>
from <http://www.snik.eu/ontology/ciox>
from <http://www.snik.eu/ontology/he>
from <http://www.snik.eu/ontology/it4it>
  {
    owl:Class ^a ?c,?d.
    graph ?g {?c ?p ?d.}
    filter(?p!=meta:subTopClass)
  }
https://www.snik.eu/sparql?query=select%20%20%3Fc%20%3Fp%20%3Fd%20%3Fg%0A%20%20from%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Flimes-exact%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fmatch%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fpersian%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fmeta%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fbb%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fob%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fciox%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fhe%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fit4it%3E%0A%20%20%7B%0A%20%20%20%20owl%3AClass%20%5Ea%20%3Fc%2C%3Fd.%0A%20%20%20%20graph%20%3Fg%20%7B%3Fc%20%3Fp%20%3Fd.%7D%0A%20%20%20%20filter(%3Fp!%3Dmeta%3AsubTopClass)%0A%20%20%7D&format=json
sparql-properties
layout
...layout applied with 100% overlap.
select
  ?c as ?uri
  group_concat(distinct(str(?l));separator="|") as ?l
  group_concat(distinct(str(?al));separator="|") as ?al
  group_concat(distinct(str(?cml));separator="|") as ?cml
  group_concat(distinct(str(?def));separator="|") as ?def
  from <http://www.snik.eu/ontology/meta>
from <http://www.snik.eu/ontology/bb>
from <http://www.snik.eu/ontology/ob>
from <http://www.snik.eu/ontology/ciox>
from <http://www.snik.eu/ontology/he>
from <http://www.snik.eu/ontology/it4it>
from <http://www.snik.eu/ontology/limes-exact>
from <http://www.snik.eu/ontology/match>
  {
    ?c a owl:Class.
    OPTIONAL {?c rdfs:label ?l.}
    OPTIONAL {?c skos:altLabel ?al.}
    OPTIONAL {?c skos:definition ?def.}
    OPTIONAL {?c skos:closeMatch|^skos:closeMatch ?cm. ?cm rdfs:label|skos:altLabel ?cml.}
  }
https://www.snik.eu/sparql?query=select%0A%20%20%3Fc%20as%20%3Furi%0A%20%20group_concat(distinct(str(%3Fl))%3Bseparator%3D%22%7C%22)%20as%20%3Fl%0A%20%20group_concat(distinct(str(%3Fal))%3Bseparator%3D%22%7C%22)%20as%20%3Fal%0A%20%20group_concat(distinct(str(%3Fcml))%3Bseparator%3D%22%7C%22)%20as%20%3Fcml%0A%20%20group_concat(distinct(str(%3Fdef))%3Bseparator%3D%22%7C%22)%20as%20%3Fdef%0A%20%20from%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fmeta%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fbb%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fob%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fciox%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fhe%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fit4it%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Flimes-exact%3E%0Afrom%20%3Chttp%3A%2F%2Fwww.snik.eu%2Fontology%2Fmatch%3E%0A%20%20%7B%0A%20%20%20%20%3Fc%20a%20owl%3AClass.%0A%20%20%20%20OPTIONAL%20%7B%3Fc%20rdfs%3Alabel%20%3Fl.%7D%0A%20%20%20%20OPTIONAL%20%7B%3Fc%20skos%3AaltLabel%20%3Fal.%7D%0A%20%20%20%20OPTIONAL%20%7B%3Fc%20skos%3Adefinition%20%3Fdef.%7D%0A%20%20%20%20OPTIONAL%20%7B%3Fc%20skos%3AcloseMatch%7C%5Eskos%3AcloseMatch%20%3Fcm.%20%3Fcm%20rdfs%3Alabel%7Cskos%3AaltLabel%20%3Fcml.%7D%0A%20%20%7D&format=json
layout

**Comment by KonradHoeffner** [comment]
Das ist das Logbuch, das stellen wir automatisch in die Issues, damit wir genau wissen, was die Benutzer gemacht haben, um den Fehler besser nachvollziehen zu können. @ThomasPause: Vielleicht müssen wir das etwas kompakter aufzeichnen.

Nach dem Log sieht es so aus, als ob sie das tight layout außerhalb des Sternmodus auf den ganzen Graphen angewendet haben. Dafür haben wir das eigentlich nicht gedacht, da es für kleine Graphen gedacht war, die zu weit auseinander standen. Der große Graph ist ja schon recht voll. Ich habe aber jetzt einen Fix eingebaut, der hoffentlich das tight layout auch auf dem vollständigen Graphen ermöglicht. Ist online im pgraph.

Auf dem Bild ist links tight layout, rechts das normale. Können sie es nochmal probieren im pgraph? Ich kann es leider nicht testen, da bei meinem PC es auch vorher nicht abgestürzt ist.

![layout-tight-normal](https://user-images.githubusercontent.com/839577/56367668-109bb600-61f6-11e9-9cff-f65779f75fb2.png)

**Comment by AlfredWinter** [comment]
Schreiben Sie doch vor das Logbuch, dass es das Logbuch ist und das für die Entwickler wichtig ist, und man das nicht ändern sollte und man davor seine Kommentare schreiben soll. 

Nein, ich hatte das tight layout im Sternmodus verwendet.

**Comment by ThomasPause** [comment]
Ja, der Log ist wirklich ganz schoen lang. Das werden wir kuerzen und entsprechend markieren.

**Comment by AlfredWinter** [comment]
Habs ausprobiert. Jetzt gehts :-) Vielleicht gab es ja auf der Strecke nach Großpösna ein Schlagloch.

**Comment by AlfredWinter** [comment]
bei graph hängt es aber immer noch. Also war es wohl doch kein Schlagloch.

**Comment by KonradHoeffner** [comment]
Hm es könnte an der underschiedlichen CPU liegen, da muss ich vielleicht weniger Zyklen benutzen. Was für ein Rechner ist das denn? Auf dem Intel Core i7-4790 @ 3.6 GHz hier geht es.

**Comment by AlfredWinter** [comment]
es ist jedesmal derselbe Rechner. Nur einmal rufe ich graph und einmal pgraph auf

**Comment by KonradHoeffner** [comment]
@ThomasPause: Kannst du mal ein paar Stresstests machen und das Log von oben nachstellen, ob du es auf dem Dobby zum Absturz bringen kannst? Danach müssen wir herausfinden, woran es liegt und das beheben.

**Comment by ThomasPause** [comment]
can not reproduce the bug on my engine (Intel Core i5-8400, 8GB RAM, Firefox 68.0b12) and also on my iPad Pro (2017, 2ndGen, Safari 12).
It lasts a while (~15sec) on the whole graph but works fine
Closed for now
