### ISSUE TITLE
put layout buttons functionality in operations

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#206]
..to clean the view

**Comment by ThomasPause** [comment]
talk about the custom layout, is it a needed feature?

**Comment by KonradHoeffner** [comment]
Clean is good but at least "reset view" and "recalculate layout" should be buttons again because we use them so often. If they take too much space, we can use icons instead of text.

**Comment by AlfredWinter** [comment]
- Rename "Operations" to "Layout", move 
- add shortcuts, see #211
- Add "Layout Help" to Help menu
- hide slider for custom layout or move it into the menu
- custom layout to expert mode
