### ISSUE TITLE
Wie hängen die Teilontologien zusammen?

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#217]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Ich wünsche mir (mit mittlerer Priorität) folgende Auswertungsmöglichkeit:
[Wie hängen die Teilontologien zusammen.pdf](https://github.com/IMISE/snik-cytoscape.js/files/3321108/Wie.hangen.die.Teilontologien.zusammen.pdf)
Vor dem Realisieren noch mal kurz mit mir besprechen.

**Comment by KonradHoeffner** [comment]
Erledigt in https://github.com/IMISE/snik-cytoscape.js/commit/9c3103f7589ee55f1e5ca81610d491e0bcac1378.
Ging allerdings nur als Kreislayout, nicht in zwei vertikalen Reihen.
Zugänglich über "Layout" -> "subontology connectivity".

![snik](https://user-images.githubusercontent.com/839577/82835136-6cd60c80-9ec3-11ea-9f5d-a20eeb8321c1.png)
