### ISSUE TITLE
Menü auch bei Rechtsklick ohne Halten

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#22]

**Comment by T-P-1** [comment]
I investigated this on https://github.com/cytoscape/cytoscape.js-cxtmenu.
it seems that there is no way to use the cxtmenu in another way than 'cxttapstart taphold'

**Comment by T-P-1** [comment]
seems to work also on mobile devices (Samsung Galaxy S8+ with firefox 63.0.2)
