### ISSUE TITLE
Combine Matches

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#233]
Please type your issue here:
Das Combine funktioniert nicht, wenn man zusätzliche Knoten ins Bild holt. Der Workaround, dann das Combine aus- und dann wieder einzuschalten, führt aber dazu, dass Knoten, die vorher sorgsam übereinandergelegt worden sind, wieder nebeneinander sortiert werden. Dann muss man die alle wieder zentrieren.
Wünsche:
1. Beim Ausschalten von Combine NICHT die Knoten irgendwie sortieren.
2. Auch bei Einschalten von Combine NICHT die Knoten sortieren. Stattdessen eine Funktion, die für alle combine matches die jeweiligen Knoten zentriert.
3. Combine auch dann durchführen, wenn neue Knoten zum Bild hinzukommen.
AW

!!Please do not delete the following text, because its the log for developers!!

```
Parameter "empty" detected. Skip loading and display file load prompt.
Load Graph from File: Visible fraction: 0.020953660174613836 set star mode to true
JSON File downloaded: snik.json
```

**Comment by KonradHoeffner** [comment]
Ich habe jetzt angefangen das einzubauen dass man einen separaten Menüeintrag anklicken muss um die Knoten auch zu verschieben, aber gemerkt, dass es extrem übersichtlich ist, wenn man im kompletten Graphen Combine anschaltet aber nicht die Knoten verschiebt. Unten ist ein Screenshot davon. Soll das trotzdem so eingebaut werden?
![Bildschirmfoto von 2019-10-14 17-25-06](https://user-images.githubusercontent.com/839577/66762570-8a131900-eea6-11e9-9563-0d9019dbf777.png)

**Comment by AlfredWinter** [comment]
Ich verstehe Ihre Argumentation nicht ganz. Bitte kommen Sie doch mal um 13:30 in mein Büro.
AW

a-------------´v---------------------------------------------------------p 
Prof. Dr. Alfred Winter 
Universität Leipzig 
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18 
D-04107 Leipzig 
 Tel.: ++49 341-97-16107 
Fax : ++49 341-97-16109 
e-mail: alfred.winter@imise.uni-leipzig.de 
http://www.imise.uni-leipzig.de/ 
http://www.3lgm2.de



 Von:   Konrad Höffner <notifications@github.com> 
 An:   IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com> 
 Kopie:   AlfredWinter <alfred.winter@imise.uni-leipzig.de>, Author <author@noreply.github.com> 
 Gesendet:   14.10.2019 17:17 
 Betreff:   Re: [IMISE/snik-cytoscape.js] Combine Matches (#233) 


Ich habe jetzt angefangen das einzubauen dass man einen separaten Menüeintrag anklicken muss um die Knoten auch zu verschieben, aber gemerkt, dass es extrem übersichtlich ist, wenn man im kompletten Graphen Combine anschaltet aber nicht die Knoten verschiebt. Unten ist ein Screenshot davon. Soll das trotzdem so eingebaut werden?

**Comment by KonradHoeffner** [comment]
# Protokoll
Ziel ist es, Schritt für Schritt einen Teilgraphen zu entwickeln und manuell das Layout anzupassen.
Dabei verwendete Operationen sollen diese Ansicht dann nicht verschieben, um bereits erledigte Anpassungen nicht wieder zu verlieren.
Die im Bild sichtbaren überlappenden Boxen sind OK.
Dafür sollen zwei neue Buttons entstehen:
1. Nebeneinander positionieren von "Geschwistern" (Kindknoten mit dem selben kombierenden Elternknoten) -> das ist die derzeitige automatische Funktionalität, die in der feature branch auch schon so implementiert wurde
2. Wie 1. aber auf exakt dieselbe Position bringen

**Comment by AlfredWinter** [comment]
Wo fiindet man die Funktion zum Positionieren?
AW
