### ISSUE TITLE
Tight Layout

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#234]
Please type your issue here:

Wunsch: Tight-Layout nur auf eine Teilmenge von Knoten anwenden, die vorher selektiert worden sind.
AW

!!Please do not delete the following text, because its the log for developers!!

```
Parameter "empty" detected. Skip loading and display file load prompt.
Load Graph from File: Visible fraction: 0.020953660174613836 set star mode to true
JSON File downloaded: snik.json
```

**Comment by KonradHoeffner** [comment]
Ich habe das jetzt eingebaut aber ich bin mir nicht sicher, ob das herauskommt, was Sie möchten. Wenn das Layout auf eine Teilmenge angewendet wird, dann ignoriert er alle anderen Knoten und dann kann es zu Überlappungen kommen. Sie können es ja mal testen und Bescheid sagen, ob das so gut ist oder ob sie da andere Vorstellungen haben.

**Comment by KonradHoeffner** [comment]
- [ ] Zentrum der selektierten Knoten soll gleich bleiben, also nach Layout dort wieder hinschieben.
- [ ] Testen, ob dadurch das Überlappungsproblem in der Praxis selten genug auftritt.
