### ISSUE TITLE
Personalisierte Ansicht

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#237]
Neben der derzeitigen globalen Ansicht sind persistente zusätzliche Arbeitsbereiche (in Tabs?) gewünscht. Dabei sollen Benutzer sich anmelden können und Teilgraphen von der Gesamtansicht in neue Views schieben können und zurück. Das ist wahrscheinlich eine größere Aufgabe.

**Comment by KonradHoeffner** [comment]
Weitere Notizen:

Arbeitsfläche
Einloggen
Persönlicher View
Schritt für Schritt Gesamtsicht in View schieben in Arbeitsbereich in beide Richtungen
Schritt für Schritt Grafik entwickeln, ohne dass alles verschiebt.
star
reset view

**Comment by ThomasPause** [comment]
Teil meiner BA, wird anders aufgeteilt in neuen Issues
