### ISSUE TITLE
close matches zeigen

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#240]
Please type your issue here:
Ich hätte gerne im Kontextmenü eines Knotens die Möglichkeit, alle CloseMatches zum Knoten einzublenden.

!!Please do not delete the following text, because its the log for developers!!

```
Separate subontologies unchecked
```

**Comment by KonradHoeffner** [comment]
Kann das als Unterfunktion vom filtered star von Issue #230 implementiert werden oder soll es ein vollwertiger Kontextmenüeintrag sein?
Es ist kein Problem das einzubauen, das Kontextmenü wird nur langsam ziemlich voll, daher wäre das Eingliedern in den filtered star eine platzsparende Alternative.

**Comment by KonradHoeffner** [comment]
Im Rahmen von https://github.com/IMISE/snik-cytoscape.js/issues/239 eingebaut.
