### ISSUE TITLE
Reports zu einem Knoten funktionieren nicht mehr

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#242]
Please type your issue here:

Wenn man zu einem Knoten edit/report wählt, dann kommt ein Warnhinweis und dann nichts mehr. 
Ich arbeite gerade mit Chrome
AW

!!Please do not delete the following text, because its the log for developers!!

```
Separate subontologies unchecked
Separate subontologies unchecked
Separate subontologies unchecked
```

**Comment by KonradHoeffner** [comment]
Ich habe das mit Firefox 72 und mit Chrome 79 getestet und bei beiden ging es. Hat der Chrome vielleicht einen Popupblocker? Was sagt denn der Warnhinweis?
