### ISSUE TITLE
class use funktioniert nicht mehr

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#243]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser: Chrome!
Class use funktioniert nicht mehr: Bildschirm wird leer und es sieht so aus, also ob die Software sich aufhängt. Z.B. bei ProjectManager

**Comment by KonradHoeffner** [comment]
Konnte ich auf dem Firefox 72 und mit Chrome 79 leider nicht nachstellen, vielleicht war das ein temporärer Fehler? Wenn es wieder auftritt, dieses Ticket bitte wieder öffnen.

**Comment by AlfredWinter** [comment]
SNIK ist immer noch down, oder?
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
twitter: @MedInfoL
instagram: medinfo.unileipzig
 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Freitag, 27. Dezember 2019 16:43
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] class use funktioniert nicht mehr (#243)
 
Konnte ich auf dem Firefox 72 und mit Chrome 79 leider nicht nachstellen, vielleicht war das ein temporärer Fehler? Wenn es wieder auftritt, dieses Ticket bitte wieder öffnen.
