### ISSUE TITLE
Star für Compound in Teilgraph

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#245]
Please type your issue here:

Wenn ich in einem Teilgraph (z.B. nach einem Star) für einen Compound einen Star mache, dann fliegt alles weg, was bisher in dem Teilgraph drin war. 

Wir brauchen dringend ein allgemeines Konzept, wie man sich schrittweise Teilgraphen aufbauen und diese erweitern kann. Da hatte ich schon was zu geschrieben. Siehe auch #237 

!!Please do not delete the following text, because its the log for developers!!

```
Loaded layout from cache, applying 2662 positions...
Separate subontologies unchecked
Separate subontologies unchecked
...0/2653 node positions set. 7026 superfluous layout positions .
Precision of 0 less than minimal required precision of 0.5.
Load Graph from File: Visible fraction: 0.02433817250213493 set star mode to true
JSON File downloaded: snik.json
```

**Comment by KonradHoeffner** [comment]
Mittlerweilse scheint es zu funktionieren. Ich habe mal mehrere Stars hintereinander gebildet inklusive Compounds und da blieb alles stabil.

Hier ist ein Video davon: [snik-2020-01-22_16.04.zip](https://github.com/IMISE/snik-cytoscape.js/files/4097880/snik-2020-01-22_16.04.zip)

@AlfredWinter: Falls das Problem doch nochmal auftreten sollte, bitte diese Issue wieder aufmachen und schreiben, wie sich das Problem reproduzieren lässt.

**Comment by AlfredWinter** [comment]
Das Video hat keinen Datei-Typ. Womit kann man sich das Video ansehen?

**Comment by KonradHoeffner** [comment]
Ich habe es mit dem VLC geöffnet, aber es könnte auch mit einem anderen player gehen, vielleicht muss man bei Windows die Dateiendung in .avi ändern? 

Es ist jetzt aber auch auf youtube (nicht gelistet): https://www.youtube.com/watch?v=0jFeKmF-QFo

**Comment by AlfredWinter** [comment]
Problem besteht noch - vielleicht ist es aber ein anderer Aspekt. 
ich habe in einem Subgraphen den CIO und auch Information Management Board mit den Close Matches. Dann bewege ich die Close Matches jeweils auf einen Punkt und mache die Kästen drumrum. Dann mache ich einen Star auf Information Management Board. Und Schwups fliegen die bisher aufeinanderliegenden Knoten wieder voneinander weg.

**Comment by KonradHoeffner** [comment]
Das war mein Fehler, ich habe es mit der neuesten Version lokal getestet aber die war noch nicht online. Jetzt sind beide auf dem gleichen Stand, können Sie es nochmal probieren?

**Comment by AlfredWinter** [comment]
jetzt geht graph nicht mehr

**Comment by KonradHoeffner** [comment]
Geht es jetzt?

**Comment by AlfredWinter** [comment]
ja
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
twitter: @MedInfoL
instagram: medinfo.unileipzig
 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner <notifications@github.com> 
Gesendet: Freitag, 24. Januar 2020 15:52
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Mention <mention@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Star für Compound in Teilgraph (#245)
 
Geht es jetzt?

**Comment by AlfredWinter** [comment]
aber jetzt hört der Kreisel gar nicht mehr auf

**Comment by KonradHoeffner** [comment]
OK ich brauche kurz eine halbe Stunde um das alles zu aktualisieren. Ich melde mich wenn alles getestet ist.

**Comment by KonradHoeffner** [comment]
Bis können Sie auch den https://www.snik.eu/pgraph/ probieren.

**Comment by AlfredWinter** [comment]
ok, bei pgraph gehts

**Comment by AlfredWinter** [comment]
auf falschen Knopf gedrückt

**Comment by KonradHoeffner** [comment]
So, jetzt funktioniert auch das normale SNIK Graph wieder.
