### ISSUE TITLE
Panzoom

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#263]
What to do with Panzoom in the future? 
Is it still needed (mobile support) vs. is it disturbing in future releases with multi window.
Discussion in next meeting

**Comment by KonradHoeffner** [comment]
We discussed this in the SNIK jour fixe on 2020-03-17. Decision: Include it in every window but try to decrease it's size.

**Comment by ThomasPause** [comment]
maybe it is better to place it in another place on the screen and make it globally useable

**Comment by ThomasPause** [comment]
is it better to just include a + and a - into the new 'global' menu? this has the benefit that we can exclude this dependency

**Comment by ThomasPause** [comment]
so for now minimal zoom elements are added in each tab/window of the multiwindow function; panzoom is deleted
