### ISSUE TITLE
Correct height of cytoscape containers inside golden layout components

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#273]
Apparently it is very hard to have an HTML div use 100% of it's available height, as just `style="height:100%;"` does not work.
Right now we use `100vh` for the height of the cytoscape container but that is too high, even though we may not see it as it is occluded by the other elements but it may produce subtle problems and it may impact performance.

See
- https://stackoverflow.com/questions/90178/make-a-div-fill-the-height-of-the-remaining-screen-space
- https://stackoverflow.com/questions/1122381/how-to-force-child-div-to-be-100-of-parent-divs-height-without-specifying-pare
- https://stackoverflow.com/questions/14628838/css-div-100-height
- https://www.codeinwp.com/snippets/make-div-100-height-of-browser-window/
- https://www.lifewire.com/set-height-html-element-100-percent-3467075
- https://stackoverflow.com/questions/28352873/css-height-100-vs-height-inherit/28352920

**Comment by KonradHoeffner** [comment]
Is this still an issue? I don't see any problems in the current version or is that just a workaround?

**Comment by ThomasPause** [comment]
i do not see any problems right now, so i think its ready to be closed for now.
