### ISSUE TITLE
open new models in separate tabs

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#276]
GoldenLayout provides several options for adding new items to the screen.
http://golden-layout.com/tutorials/dynamically-adding-components.html
Which is best for us?
Investigate on how it is best located and implement it.

**Comment by ThomasPause** [comment]
best option is the third and we define a stack environment with one tab holding the whole graph

**Comment by ThomasPause** [comment]
todo: change the symbol used to create a new model

**Comment by KonradHoeffner** [comment]
https://golden-layout.com/docs/EventEmitter.html

**Comment by ThomasPause** [comment]
now that all is done, the initial setting is to be defined: in my opinion at the beginning there should be only one tab with the name "Gesamtmodell SNIK" and via clicking on new tab, new tabs with the names "Teilmodell n" should open.

**Comment by KonradHoeffner** [comment]
> now that all is done, the initial setting is to be defined: in my opinion at the beginning there should be only one tab with the name "Gesamtmodell SNIK" and via clicking on new tab, new tabs with the names "Teilmodell n" should open.

That sounds great for production. However for testing it could be quicker to always start with at least one partial model.
