### ISSUE TITLE
Unknown bug while searching

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#278]
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data log.js:33:10
    f https://www.snik.eu/graph/js/browser/log.js:33
    select https://www.snik.eu/graph/js/sparql.js:41
Error executing SPARQL query:
select
  ?c as ?uri
  group_concat(distinct(str(?l));separator="|") as ?l
  group_concat(distinct(str(?al));separator="|") as ?al
  group_concat(distinct(str(?cml));separator="|") as ?cml
  group_concat(distinct(str(?def));separator="|") as ?def
  from <http://www.snik.eu/ontology/meta>
from <http://www.snik.eu/ontology/bb>
from <http://www.snik.eu/ontology/ob>
from <http://www.snik.eu/ontology/ciox>
from <http://www.snik.eu/ontology/he>
from <http://www.snik.eu/ontology/he-unconsolidated>
from <http://www.snik.eu/ontology/it4it>
from <http://www.snik.eu/ontology/limes-exact>
from <http://www.snik.eu/ontology/match>
  {
    ?c a owl:Class.
    OPTIONAL {?c rdfs:label ?l.}
    OPTIONAL {?c skos:altLabel ?al.}
    OPTIONAL {?c skos:definition ?def.}
    OPTIONAL {?c skos:closeMatch|^skos:closeMatch ?cm. ?cm rdfs:label|skos:altLabel ?cml.}
  }
URL: https://www.snik.eu/sparql?query=select%0A%20%20%3Fc%20as%20…label%7Cskos%3AaltLabel%20%3Fcml.%7D%0A%20%20%7D&format=json

**Comment by KonradHoeffner** [comment]
The query is missing the <> characters but with a real query:
```
select
  ?c as ?uri
  group_concat(distinct(str(?l));separator="|") as ?l
  group_concat(distinct(str(?al));separator="|") as ?al
  group_concat(distinct(str(?cml));separator="|") as ?cml
  group_concat(distinct(str(?def));separator="|") as ?def
  from <http://www.snik.eu/ontology/meta>
from <http://www.snik.eu/ontology/bb>
from <http://www.snik.eu/ontology/ob>
from <http://www.snik.eu/ontology/ciox>
from <http://www.snik.eu/ontology/he>
from <http://www.snik.eu/ontology/he-unconsolidated>
from <http://www.snik.eu/ontology/it4it>
from <http://www.snik.eu/ontology/limes-exact>
from <http://www.snik.eu/ontology/match>
  {
    ?c a owl:Class.
    OPTIONAL {?c rdfs:label ?l.}
    OPTIONAL {?c skos:altLabel ?al.}
    OPTIONAL {?c skos:definition ?def.}
    OPTIONAL {?c skos:closeMatch|^skos:closeMatch ?cm. ?cm rdfs:label|skos:altLabel ?cml.}
  }
```
The estimated query execution time is too long so the SPARQL endpoint rejects it. The reason is that there are too many optional clauses. There is no perfect solution here but I will remove the optional from the label under the assumption that every class has at least one label, which should improve the (estimated or real) runtime of the query and hopefully push it under the limit.
