### ISSUE TITLE
Ergebnis einer Suche kann nicht markiert und kopiert werden

### ISSUE THREAD

**Issue by kuechererSWE** [IMISE/snik-cytoscape.js#28]
Nach Eingabe eines Suchstrings z.B. Strategic erscheinen links mit schwarzem Hintergrund die Treffer.
Einer der Treffer kann ausgewählt werden, um in der Ontologie angezeigt zu werden.
Der Text des Suchtreffers (z.B. Strategic_Information_Management_Plan) lässt sich aber nicht selektieren und kopieren.  Das wäre ein schönes Feature, um mit der Ontologie zu arbeiten.

**Comment by KonradHoeffner** [comment]
Man kann es schon markieren, man muss nur mit der Maus außerhalb der Textbox anfangen. Wenn das immer noch nicht geht, issue wieder öffnen.
