### ISSUE TITLE
Details zu Konzepten fehlen

### ISSUE THREAD

**Issue by kuechererSWE** [IMISE/snik-cytoscape.js#29]
Wenn eine Klasse der Ontologie ausgewählt wird mit rechtsklick auf das Konzept kommt u.a. die Auswahl "description". Dies führt auf eine Detailseite, z.B. http://linkedspending.aksw.org/snik/page/Operational_Information_Management
Leider gibt es dort keine nennenswerte Details. Wünschenswert wäre die Anzeige der Definition und weitere Details, die bei der Extraktion der Ontologie erstellt wurden. Ist es möglich dieses Feature zu vervollständigen?

**Comment by KonradHoeffner** [comment]
Ontologie v0.3 ist sehr bald fertig, dann wird auf deren Grundlage ein neuer RDF Browser aufgesetzt.

**Comment by KonradHoeffner** [comment]
Added in commit 6caafecd4ae8d6372608921ee9ddc073b6969596.
