### ISSUE TITLE
Discussion SNIK Jour fixe 15.9.2020

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#299]
things to discuss/show:
- workflow demonstration (OB-->System-->Informationssystem)
- usability: size of icons, keys for copy/paste vs. Buttons
- scopes of menu-entries (esp. filter/options)
- what has to be saved/loaded?
- ui tests
- conversion (hint: Schlagumstellung)

**Comment by KonradHoeffner** [comment]
# Protokoll
## Participants
- AW, BS, FJ, TP, KH

## Actions

### Developers
- [ ] Make deletion of nodes official. Discuss deleting of nodes
- [ ] Fix copy and paste key messages when typing in parts like the search field.
- [ ] Adapt menu and golden layout to day mode.

### Bachelor Thesis Future Work
- [ ] automatic alignment on grid 
- [ ] "snap" node positions on grid lines

## Minutes

## Questions
### How can we search when the partial graph is empty?
It is not empty, instead the nodes are hidden by default on new tabs.
On paste, the pasted nodes are just made visible in the target tab.

**Comment by ThomasPause** [comment]
- [ ] Warnung anzeigen, wenn Load Session ausgeführt wird, dass komplette Sitzung überschrieben wird

**Comment by ThomasPause** [comment]
outsourced in new issues, so close this one
