### ISSUE TITLE
Copying in new tab hides the label of edges

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#322]
Making a partial model, copying it and pasting it into a new tab hides the labels of the edges. 
They are shown again, when making a new path operation

**Comment by KonradHoeffner** [comment]
This could be a timing issue, where Cytoscape.js does not update its ":visible" selector in time.

**Comment by KonradHoeffner** [comment]
The issue seems to be timing independent, as it also occurs when the edges are shown later via keypress.

**Comment by KonradHoeffner** [comment]
This bug is hard to track down, however `layoutState.cy.nodes(".unfiltered").not(".hidden");` seems to work while `layoutState.cy.nodes(":visible")` seems to not or only sporadically work.
If this occurs again, reopen.
