### ISSUE TITLE
Cypress lässt sich nicht auf bruchtal installieren

### ISSUE THREAD

**Issue by ThomasPause** [IMISE/snik-cytoscape.js#323]
Vorübergehende Lösung: Cypress gelöscht in package.json
Längerfristige Lösung: Cypress entweder nur lokal nutzen oder in docker packen (siehe https://www.cypress.io/blog/2019/05/02/run-cypress-with-a-single-docker-command/ )

**Comment by KonradHoeffner** [comment]
Aber vorher ging es doch, oder?
Ich probiere erstmal ein downgrade der Cypress-Version.
Außerdem ist noch die Frage, ob der Server überhaupt die Development-Pakete braucht, dann dort wird ja nicht entwickelt.
Ich investigiere mal, ob es reicht, auf dem Server nur `npm install --only=prod` auszuführen.

**Comment by KonradHoeffner** [comment]
Cypress liegt unter den dependencies, da gehört es aber nicht hin. Ich verschiebe es in die devDependencies.

**Comment by KonradHoeffner** [comment]
Ist verschoben und getestet. `npm install --only=prod` reicht.

**Comment by KonradHoeffner** [comment]
Dadurch werden 2.1 GB frei, was gerade auf dem Server mit stark beschränktem Platz wichtig ist.
