### ISSUE TITLE
Jour Fixe 2020-10-20

### ISSUE THREAD

**Issue by KonradHoeffner** [IMISE/snik-cytoscape.js#325]
Ask for approval at next jour fixe.

## To Do

- [x] remove (comment or change log level) popup about unhiding of node after search
- [x] remove (comment or change log level) popup when downloading

### On Paste
- [x] remove highlighting of existing elements after paste
- [x] highlight pasted elements
- [x] fit screen again

## Pain Points

- [ ] "save session" leads to "Open File" from Firefox, which is confusing to the user. Is there a way to change the browser open file dialog or suppress it? Asked at <https://stackoverflow.com/questions/64443265/user-confusion-between-save-download-and-open-in-a-web-application>.
- [x] Is it possible to display the changed checkbox state immediately after click on "combine matches" and other options and not only after the operation is finished? Asked at <https://stackoverflow.com/questions/64442639/how-to-give-instant-user-feedback-on-slow-checkbox-listeners-in-javascript>.
- [x] window activation is not intuitive. try again to auto activate in window.

## Restore Deleted Nodes On Paste
- [ ] when a node does not exist in the target graph, copy it and its edges from the main graph

## Steps
- create new tab
- search
- activate

## Bugs

- [x] Loading with "Combine Matches" set produces an error, moved to https://github.com/IMISE/snik-cytoscape.js/issues/326
- [x] Combine matches show in pgraph but not in graph
- [x] some nodes have a thick border that cannot be removed even if they aren't highlighted, see example.
[snik-session-highlight-bug.zip](https://github.com/IMISE/snik-cytoscape.js/files/5407149/snik-session-highlight-bug.zip)

- [x] copying from one part model to another causes edges to be hidden (bug was already fixed but occurs again)
[snik-session-edge-bug.zip](https://github.com/IMISE/snik-cytoscape.js/files/5407176/snik-session-edge-bug.zip) Update: This was indeed already resolved but <https://www.snik.eu/graph> does not always have the newest version. Updated graph and pgraph to the newest version to include the bugfix.

**Comment by AlfredWinter** [comment]
Ja, das sind ie Punkte, die wir besprochen haben.

**Comment by KonradHoeffner** [comment]
Drei Monate später gibt es immer noch keine Antwort auf https://stackoverflow.com/questions/64443265/user-confusion-between-save-download-and-open-in-a-web-application, daher gehe ich mal davon aus, dass es keine einfache Lösung für das "Save Session"-"Open File" Problem gibt und da ich das auch nicht als großes Problem ansehe, hake ich das mal ab.

**Comment by KonradHoeffner** [comment]
Combine matches was successfully tested on 2021-01-28, so check that.

**Comment by KonradHoeffner** [comment]
Window activation split out into https://github.com/IMISE/snik-cytoscape.js/issues/345.

**Comment by KonradHoeffner** [comment]
Restore Deleted Nodes On Paste split out into https://github.com/IMISE/snik-cytoscape.js/issues/346.

**Comment by AlfredWinter** [comment]
Beim Testen bin ich zunächst auf eine nicht-erwartungskonforme Verhaltensweise beim Pull-Down-Menü "Options" gestoßen: wenn man nach Üffnen der der Auswahl über die einzelnen Optionen fährt (mouse-over) werden Sie gehighlitet auch wenn man nur über den Text hovert. Wenn man aber dann auf den Text klickt passiert nichts - und man weiß aber nicht, ob das Ding was tut oder nicht. Erst wenn man auf die Checkbox clickt, dann wird die Option eingeschaltet. 
Die Option sollte auch eingeschaltet oder abgeschaltet werden, wenn man auch den Text, also nicht auf die box klickt.

**Comment by KonradHoeffner** [comment]
Das daneben Klicken habe ich in eine neue Issue https://github.com/IMISE/snik-cytoscape.js/issues/347 gepackt.

**Comment by AlfredWinter** [comment]
Habe es ausprobiert. scheint gut zu funktionieren mit dem an- und abschalten der Option combine matches.

**Comment by KonradHoeffner** [comment]
Das daneben Klicken ist jetzt auch mit eingebaut.

**Comment by AlfredWinter** [comment]
Müsste dann auch noch bei den Filtern gemacht werden.

**Comment by KonradHoeffner** [comment]
Erledigt.
