### ISSUE TITLE
Mehrfachauswahl bei Suchergebnissen

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#328]
Please type your issue here:
Es wäre schön, wenn man nach einer Suche (z.B. nach "goal") mehrere der gefundenen Einträge auswählen könnte.

!!Please do not delete the following text, because its the log for developers!!

```

Register Context Menu. Developer Entries: false, Extended Entries: false
Node is hidden. Unhiding http://www.snik.eu/ontology/ob/Goal.
Node is hidden. Unhiding http://www.snik.eu/ontology/ob/ProjectGoal.
Separate subontologies unchecked
layout
layout
Node is hidden. Unhiding http://www.snik.eu/ontology/bb/StrategicHospitalGoal.
Separate subontologies unchecked
layout
```

**Comment by KonradHoeffner** [comment]
Über "Highlight All" besteht die Möglichkeit, alle gefundenen Knoten anzuzeigen.
Allerdings war das nicht sehr sichtbar, da Text nicht als Link hervorgehoben wurde, das habe ich jetzt geändert.

Wenn Sie möchten, kann ich noch eine Reihe an Checkboxen hinzufügen, mit denen man eine Teilmenge zur Anzeige auswählen kann.

**Comment by AlfredWinter** [comment]
Checkboxen wären gut. 
Denn die gesamte Liste ist meist viel zu groß und enthält viele Ergebnisse, die nicht gut zur Suche passen.

**Comment by KonradHoeffner** [comment]
Ist implementiert und auf dem pgraph zu sehen.

**Comment by AlfredWinter** [comment]
Da scheint mir aber jetzt ein Bug drin zu sein: Ich habe das in einem leeren Teilnodelll versucht. Wenn ich nach CIO suche und die Wier CIO-Einträge auswähle werden die zwar gehailaitet, aber ew werden auf einmal auch alle Knoten von SNIK angezeigt. 

Ferner sind die Kommandos "highlight all/selected" nicht gut dargestellt. Die Kommandos haben dasselbe Layout wie die Tabelleneinträge und sehen aus wie die Überschriften der beiden Spalten. Kommandos müssen ein einheitliches Erscheinungsbild in ganz SNIK haben, das sie von anderen Informationen unterscheidet.
