### ISSUE TITLE
Beschriftung von Kanten

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#330]
Please type your issue here:

Manche Kanten sind beschriftet, manche nicht

!!Please do not delete the following text, because its the log for developers!!

```

Partial graph inserted!
Node is hidden. Unhiding http://www.snik.eu/ontology/bb/StrategicInformationManagementGoal.
Separate subontologies unchecked
layout
Copied 3 elements from undefined.
Partial graph copied!
Pasted 3 elements into undefined.
Partial graph inserted!
Copied 1 elements from undefined.
Partial graph copied!
Pasted 1 elements into undefined.
Partial graph inserted!
```

**Comment by KonradHoeffner** [comment]
Das scheint ein Bug beim star zu sein, ich kümmere mich darum.

**Comment by KonradHoeffner** [comment]
Die Hervorhebung war etwas inkonsistent und zu komplex durch verschiedene Stilklassen wie "highlighted" und "starmode". Ich habe das jetzt vereinfacht, sodass nur noch markierte Kanten ihre Kantenbeschriftung zeigen. Einfügen und star selektieren jetzt automatisch die dabei erzeugten Elemente.
