### ISSUE TITLE
Wunsch nach direkten Update-Möglichkeiten

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#331]
Please type your issue here:

Ich stoße immer wieder auf Fehler in der Ontologie bzw. auf Dinge, die ergänzt oder entfernt werden müssten. Ich kann dann zwar die entsprechenden Issues absetzen, aber gerade bei der Unterrichtsvorbereitung kann ich nach einigen issues nicht mehr weiterarbeiten, weil ich die gewünschten Änderungen jetzt wirklich bräuchte. 
Ich wünsche mir die Möglichkeit, direkt Änderungen in der Ontologie vornehmen zu können (Kanten und Knoten). Die Änderungen könnten ja damit verbunden sein, dass gleich automatisch ein issue erzeugt wird, dass diese Änderung noch validiert werden muss und es könnte bei der geänderten Information ein Warndreieck angezeigt werden, das erst nach Validierung wieder erlischt. 
Diese Änderung könnte man ja auch sperren und nur dann ermöglichen, wenn man ein bestimmtes Passwort eingibt (das würde eine Nutzerverwaltung ersparen)

!!Please do not delete the following text, because its the log for developers!!

```

```

**Comment by KonradHoeffner** [comment]
Dafür ist das OntoWiki da, das seit dem letzten Serverneustart in dieser Woche nicht mehr richtig funktioniert. Ich treffe mich morgen Vormittag (30.10) mit @SebStaeubert um das zu beheben und melde mich, sobald es wieder geht.

**Comment by KonradHoeffner** [comment]
Das OntoWiki ist wieder funktionsfähig. Im developer mode erreicht man es über das Kontextmenü einer Klasse über "OntoWiki".
