### ISSUE TITLE
Reset View geht nicht

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#333]
Please type your issue here:

Ich habe Gesamtmodell star gemacht und nun kriege ich nicht mehr alles angezeigt.

!!Please do not delete the following text, because its the log for developers!!

```

graph-init
Create view undefined with 7550 hidden elements copied from undefined.
Register Context Menu. Developer Entries: false, Extended Entries: false
Separate subontologies unchecked
layout
layout
```

**Comment by KonradHoeffner** [comment]
Ich konnte das Problem leider weder im Firefox noch im Chrome nachstellen. Tritt es jedes mal auf oder nur sporadisch?

**Comment by AlfredWinter** [comment]
Das problem tritt nur in einem Teilmodell auf. Aber jetzt verstehe ich, dass das Problem ja auftauchen MUSS. Denn was soll den hier ein reset view bedeuten? Folglich dürfte in Teilmodellen diese Funktion aber gar nicht angeboten werden. 

Was ich eigentlich erwartet hatte war folgendes: Wenn ich im Gesamtmodell nach einem Star ein reset view mache, dann ist der Star wieder 'weg' (weil ich wieder alle Sternchen sehe). 'Wenn ich im Teilmodell bin und nach einem Star ein reset view mache, hatte ich auch erwartet der Star ist 'weg', ich bin also wieder da wo ich vorher war. Aber wie soll das geschehen? Ich glaube statt des reset view wäre ein CTRL-Z nützlich, mit der ich ein paar Aktionen der Vergangenheit rückgängig machen könnte.

**Comment by KonradHoeffner** [comment]
Das hat Herr Pause in seiner Bachelorarbeit auf Seite 60 beschrieben: "Reset View" bezieht sich nur auf das Gesamtmodell. Da wir die Arbeit aber noch nicht haben hat und es weder im Menüeintrag noch im Mouseover steht, können Sie das natürlich nicht sehen. 

Ich habe die Bezeichung in "reset main view" geändert.

**Comment by KonradHoeffner** [comment]
Die Issue zur Undo-Funktion ist https://github.com/IMISE/snik-cytoscape.js/issues/95.
