### ISSUE TITLE
Filter und Save Session

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#335]
Please type your issue here:

Wenn man mit den Filter die EntityTypes ausfiltert, kann man die jederzeit wieder einblenden, auch in einem Teilmodell. Nun habe ich im Filter bei den EntityTypes den Haken weggenommen und dann ein Save Session gemacht. Anschließend habe ich die Session wieder geladen und dann ist der Filter wieder wie zuvor gesetzt: kein Haken bei EntityTypes. Folglich auch keine EntityTypes zu sehen. Jetzt setze ich den Haken und würde erwarten, die EntityTypes kommen wieder. Ist aber leider nicht so. Die sind jetzt alle weg. Das darf so nicht sein. 

!!Please do not delete the following text, because its the log for developers!!

```

Register Context Menu. Developer Entries: false, Extended Entries: false
Register Context Menu. Developer Entries: false, Extended Entries: false
Register Context Menu. Developer Entries: false, Extended Entries: false
Register Context Menu. Developer Entries: false, Extended Entries: false
Register Context Menu. Developer Entries: false, Extended Entries: false
```

**Comment by KonradHoeffner** [comment]
Ich kümmere mich darum.

**Comment by KonradHoeffner** [comment]
Ich kann den Fehler nachstellen. Beim ersten Klick auf die "unchecked" Checkbox passiert nichts, zwei weitere Klicks stellen die fehlenden Elemente aber wieder her. Das heißt, die Elemente sind noch vorhanden aber der Zustand der Filter wird nicht richtig initialisiert beim Laden.
