### ISSUE TITLE
Combine matches geht nicht mehr

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#339]
Please type your issue here:

!!Please do not delete the following text, because its the log for developers!!

```

Load Graph from File: Visible fraction: 1 set star mode to false
graph-init
Load Graph from File: Visible fraction: 0.01033112582781457 set star mode to true
Register Context Menu. Developer Entries: false, Extended Entries: false
Register Context Menu. Developer Entries: false, Extended Entries: false
Set combine match mode to true
Set combine match mode to false
```

**Comment by AlfredWinter** [comment]
[snik-session(2).zip](https://github.com/IMISE/snik-cytoscape.js/files/5466072/snik-session.2.zip)

combine matches geht in dem Teilmodell nicht.

**Comment by KonradHoeffner** [comment]
Waren Sie vielleicht im pgraph? Im graph geht es bei mir, im pgraph (Entwicklerversion) nicht. Vielleicht war zu dem Zeitpunkt auch eine andere Version online, können Sie es noch einmal probieren?

**Comment by KonradHoeffner** [comment]
Ich habe den Fehler jetzt behoben, momentan ist der Server aber nicht erreichbar, sobald dies behoben ist werde ich den neuen Stand auf den pgraph bringen. Bis dahin müsste es mit dem normalen graph funktionieren.

**Comment by AlfredWinter** [comment]
Ja, funktioniert.
