### ISSUE TITLE
combine Matches 

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#341]
Please type your issue here:

Ich hatte die option Combine Matches eingeschaltet und habe zu BB:Cio ein class use gemacht. Als das angezeigt wurde, waren die matches nicht mehr combined und dafür gab es eine komische Ecke (siehe Bild), wo ein Knoten hingehört aber der nicht da ist. 
![Unbenannt](https://user-images.githubusercontent.com/22190396/99430352-82277300-2909-11eb-9c9a-535b12204249.JPG)

!!Please do not delete the following text, because its the log for developers!!

```

Set combine match mode to false
Set combine match mode to true
Set combine match mode to false
```

**Comment by KonradHoeffner** [comment]
Die Option Combine Matches ist bei Class Use nicht berücksichtigt. Ich schlage vor, dass Class Use automatisch den Combine Matches-Modus beendet, sind Sie damit einverstanden?

Class Use sollte perspektivisch auch in einem neuen Tab geöffnet werden, da die multiview-Funktionalität dafür gut geeignet ist.

**Comment by KonradHoeffner** [comment]
Es ist jetzt im development build behoben. Sobald ich wieder Zugriff zum Server habe, werde ich es auf dem dort aktualisieren.

**Comment by AlfredWinter** [comment]
Jetzt habe ich nicht verstanden, was Ihr Lösungsweg ist. Combine Matches Mode beenden oder neuen Tab oder beides?

**Comment by KonradHoeffner** [comment]
Also ich habe erstmal den Combine Matches Mode beendet. Das neue Tab ist dann der nächste Schritt, aber da Combine Matches eine Option im Hauptmenü ist, muss das momentan über alle Tabs gleich sein, das heißt das würde trotzdem beendet werden.

Am besten wäre wahrscheinlich, die Combine Matches-Option in das Tabspezifische Menü einzubauen, aber das Tabspezifische Menü unterstützt momentan keine Radiobuttons, also Optionen sind momentan alle im Optionenmenü des Hauptmenüs.

**Comment by KonradHoeffner** [comment]
Der Server funktioniert wieder, die Funktionalität ist jetzt online auf dem graph und pgraph.

**Comment by KonradHoeffner** [comment]
Ich habe es jetzt so umgebaut, dass ein neues Tab erzeugt wird und dabei ist mir aufgefallen, dass ein Combine Match *nach* dem Class Use sogar funktioniert, das heißt ich werde es jetzt kurz ausmachen, dann das Combine Match erzeugen, und dann wieder anschalten.

**Comment by AlfredWinter** [comment]
Erst mal schöne zwischenDenTagenGrüße.
Ich sehe noch nicht, wieso das Combine Match etwas mit dem Class Use zu tun hat. Combine Match bedeutet doch zunächst nur, dass um die Close Matches ein Rahmen gezogen wird. Dass die gerahmten Objekte dann auch nahe beieinander liegen oder gar übereinander ist doch eine komplett andere Operation. Ich finde, das sollte auch nicht miteinander kombiniert werden. Vor diesem Hintergrund würden sich bei eingeschalteter Combine Match Option nach der Class Use Operation eben die Rahmen möglicherweise über das ganze Bild erstrecken und es könnte hässlich aussehen. Wem das dann nicht gefällt, kann entweder die Option abschalten oder aber die Layout Funktion "move matches nearby" oder "move matches on top" auswählen. Im letzteren Fall würde halt das Layout von Class Use möglicherweise zerstört - aber das ist dann ja unmittelbar nachvollziehbar. 
Mein Fazit: Sauber trennen zwischen der OPTION Combine Match und den Layout-Operationen "move matches ..."; d.h. auch beim normalen Auswählen Option Combine Match noch nicht automatisch irgendwelche Knoten bewegen.


Und wenn ich das eingeschaltet habe, dann soll es eben gemacht werden, egal ob das nac

**Comment by KonradHoeffner** [comment]
Ihnen auch viele Grüße zwischen den Feiertagen!

Also rein logisch hat das tatsächlich nicht viel miteinander zu tun, das ist nur programmiertechnisch ein Problem gewesen, weil die Art und Weise wie Class Use programmiert ist durch die Elternknoten von Combine Matches gestört wird.

Ich habe jetzt aber eine Möglichkeit gefunden, das zu beheben und lade es jetzt auf den graph und pgraph hoch. Bei mir funktioniert es jetzt, ich hoffe bei Ihnen auch, es müsste jetzt unabhängig sein, so wie Sie geschrieben haben.

**Comment by KonradHoeffner** [comment]
So, es ist jetzt online und auf dem graph getestet im Firefox 85. Der cache musste aber gelöscht werden, damit die neue Version funktioniert.

**Schritte**
* Combine Matches anschalten
* "CIO" Suchen
* bb:CIO auswählen
* Class Use auswählen

![class-use-combine-matches](https://user-images.githubusercontent.com/839577/103283463-eb0a0c80-49d8-11eb-9a04-7b61eba17166.png)

**Comment by AlfredWinter** [comment]
Nee, wenn ich combine matches anhake, zieht er die  gerahmten Knoten nahe zueinander.

**Comment by KonradHoeffner** [comment]
Achso, das ist seit mindestens einem Jahr Standardfunktionalität, da es im Gesamtgraphen immer benötigt wird und man sich dadurch einen Klick spart und die Benutzer nicht verwirrt. Ich kann das für diesen Spezialfall ausschalten.

**Comment by KonradHoeffner** [comment]
So, ich habe jetzt eine Ausnahme eingebaut, dass beim initialen Anwenden von Combine Match beim Class Use kein move vorgenommen wird. Es sieht jetzt so aus, ist das so OK für Sie?
![class-use-combine-match-nomove](https://user-images.githubusercontent.com/839577/103284349-4c32df80-49db-11eb-9d6e-deb930a84be8.png)

**Comment by AlfredWinter** [comment]
Spezialfälle und Ausnahmen halte ich für gefährlich, Das wird immer wieder zu Problemen führen. Ich schlage vor, dass generell das Zusammenziehen der Knoten NICHT erfolgt, wenn die option Combine Matches eingeschaltet wird - auch wenn das bisher Standardfunktionaliät ist. Zusammenziehen nur dann, wenn das als Layoutfunktion explizit beauftragt wird.

**Comment by AlfredWinter** [comment]
Nein, besser gar nichts automatisches!

**Comment by AlfredWinter** [comment]
Ich sehe auch bei dem Class use nichts Spezielles, das eine besonderheit erfordern würde.

**Comment by AlfredWinter** [comment]
Mal telefonieren?

**Comment by KonradHoeffner** [comment]
Ergebnis Telefonat: Wie von Herr Winter vorgeschlagen generell Combine Matches und Move Nearby trennen. Temporär einen Nutzerhinweis anzeigen, um den Übergang zu erleichtern.

**Comment by KonradHoeffner** [comment]
Die Änderungen sind jetzt umgesetzt aber jetzt tritt ein Fehler auf. Investigate.

```
Uncaught (in promise) Error: Can not create second element with ID `parent3`
    Ee file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:23
    restore file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    Oe file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:23
    add file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    combineMatch file:///home/konrad/projekte/snik/cytoscape/js/browser/graph.js:509
    default file:///home/konrad/projekte/snik/cytoscape/js/browser/progress.js:42
    combineMatch file:///home/konrad/projekte/snik/cytoscape/js/browser/graph.js:460
    classUse file:///home/konrad/projekte/snik/cytoscape/js/browser/classuse.js:140
    classUse file:///home/konrad/projekte/snik/cytoscape/js/browser/classuse.js:140
    select file:///home/konrad/projekte/snik/cytoscape/js/browser/contextmenuNodes.js:85
    addEventListeners file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape-cxtmenu/cytoscape-cxtmenu.js:613
    o file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    trigger file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    Oi file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    trigger file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    emit file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    trigger file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    Oi file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    trigger file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    emit file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    trigger file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    Oi file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    trigger file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    emit file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:29
    load file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    o file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    registerBinding file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    load file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    notify file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    notify file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    initRenderer file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    Ua file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    dl file:///home/konrad/projekte/snik/cytoscape/node_modules/cytoscape/dist/cytoscape.min.js:32
    Graph file:///home/konrad/projekte/snik/cytoscape/js/browser/graph.js:33
    View file:///home/konrad/projekte/snik/cytoscape/js/browser/view.js:78
    main file:///home/konrad/projekte/snik/cytoscape/js/browser/main.js:203
    EventListener.handleEvent* file:///home/konrad/projekte/snik/cytoscape/js/browser/main.js:211
```

**Comment by KonradHoeffner** [comment]
OK, Fehler behoben und es ist online im graph und pgraph. Eventuell ist Cache löschen nötig.

**Comment by AlfredWinter** [comment]
Ja, geht. Mal sehen, wie die Kundschaft reagiert ...
