### ISSUE TITLE
Fehlermeldung bei Auswahl der Sprache in pgraph

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#349]
Please type your issue here:

![image](https://user-images.githubusercontent.com/22190396/106926067-fdcadc00-6710-11eb-9f0c-6ae1da071adb.png)
bin im pgraph. Fehlermeldung bei Auswahl der Sprache.

!!Please do not delete the following text, because its the log for developers!!

```

UpdateHtml: i18n keys showInstances,deselect-all,search-field,base-mode,context-menu,incoming-star,outgoing-star,combine-close-matches,class-use not used
Set language from de to fa.
Set language from fa to en.
UpdateHtml: i18n keys showInstances,starNewView,deselect-all,search-field,base-mode,context-menu,incoming-star,outgoing-star,combine-close-matches,class-use not used
```

**Comment by KonradHoeffner** [comment]
Die Warnung ist jetzt entfernt, siehe auchIssue https://github.com/IMISE/snik-cytoscape.js/issues/357.
