### ISSUE TITLE
http://www.snik.eu/ontology/bb/StrategicInformationManagementGoal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#352]
Problem with the class [bb:StrategicInformationManagementGoal](http://www.snik.eu/ontology/bb/StrategicInformationManagementGoal) ([OntoWiki URL](https://www.snik.eu/ontowiki/view/?r=http://www.snik.eu/ontology/bb/StrategicInformationManagementGoal&m=http://www.snik.eu/ontology/bb)):

wird nicht gefunden bei "strategisches Ziel" oder bei "starategic goal"

**Comment by KonradHoeffner** [comment]
OK, ich habe das Problem gefunden, es lag am `location`-Parameter des Suchindexes, der Stellen am Anfang der Definition bevorzugt hatte. Die Positionssensitivität hatte ich letztens schon in e4895ee5cea83dfbd8c5a244012b9e2d5fee8713 entfernt aber auf dem Server war noch die stabile Version. Ich habe jetzt die allerneueste Version auf <https://www.snik.eu/graph> gepackt, damit findet man es dort jetzt auch mit "starategic goal".

Es ist der Suche jetzt also egal, ob das Suchwort in einer langen Definition ganz am Ende oder am Anfang vorkommt.
