### ISSUE TITLE
Indikator für has instances

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#354]
Please type your issue here:

zumindest bei https://www.snik.eu/ontology/bb/StrategicInformationManagementGoal wird kein Sternchen angezeigt, obwohl Instances verlinkt sind. 

!!Please do not delete the following text, because its the log for developers!!

```

```

**Comment by KonradHoeffner** [comment]
Da gab es einen Fehler, dass die generell nicht angezeigt wurden, dieser Fehler ist jetzt behoben.
