### ISSUE TITLE
Sprachauswahl

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#357]
Bei der Auswahl der Sprache erscheint rechts unten ein unverständlicher Hinweis: "Updaten HTML; I18n keys...."

!!Please do not delete the following text, because its the log for developers!!

```

Set language from en to de.
UpdateHtml: i18n keys showInstances,deselect-all,search-field,base-mode,context-menu,incoming-star,outgoing-star,combine-close-matches,class-use not used
Set language from de to en.
UpdateHtml: i18n keys showInstances,starNewView,deselect-all,search-field,base-mode,context-menu,incoming-star,outgoing-star,combine-close-matches,class-use not used
```

**Comment by KonradHoeffner** [comment]
Der Hinweis war eigentlich nur für Entwickler gedacht, ich habe ihn aus dem Popup entfernt, er ist jetzt nur noch in der Entwicklerkonsole zu sehen.
