### ISSUE TITLE
Spiderworm nicht veränderbar

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#42]
wenn man einen Spiderworm erzeugt, wird er separat angezeigt. Früher konnte man dann die Positionen der einzelnen Knoten verändern. Das geht nicht mehr. Ist aber wichtig.

Gruß, Alfred Winter

**Comment by KonradHoeffner** [comment]
Welchen Browser benutzen Sie? Im Firefox habe ich das Problem nicht aber im Chrome.

**Comment by KonradHoeffner** [comment]
Ich glaube man muss da nur genau in den Kreis klicken. Außerdem kann es auftreten wenn man die Browser-Zoom-Funktion benutzt. Wenn man nur im Cytoscape zoomt und nicht mit dem browser müsste es gehen. Daher schließe ich das erstmal, wenn es trotzdem Auftritt, bitte wieder öffnen.
