### ISSUE TITLE
"set as path target" im Kontext-Menü ...

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#44]
... funktioniert nicht. Set as path source funktioniert aber.
AW

**Comment by KonradHoeffner** [comment]
Erfolgreich getestet bei:
- mir: Firefox 50.0.2 64 Bit, Google Chrome 55.0.2883.87 (64-bit), Linux
- Marful: Firefox 49.0.1 und Internet Explorer 11 (aber langsam), Windows

Daher schließe ich das hier erstmal, vielleicht hat sich das ja seitdem durch eine Änderung erledigt.

Wenn es doch noch auftritt, bitte Ticket wieder öffnen, Browserversion angeben, Browser aktualisieren und angeben, ob es mit einem aktualisierten Browser immer noch passiert.

Achtung: Internet Explorer wird nicht unterstützt, wenn es was von Microsoft sein soll bitte Microsoft Edge nehmen.
