### ISSUE TITLE
Remote Function Call

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#45]
Bei der Suche nach "Remote" werden 2 Knoten mit dem Namen "Remote Function Call" und dem Zusatz bb gefunden. 

- Das scheint mir ein Fehler zu sein, denn es sollte im bb den Begriff nur 1 mal geben. 

- Für beide Begriffe wird die Fehlermeldung angezeigt, dass die Sucheregebnisse nur im Sparql-Endpunkt enthalten sind, nicht aber im Graph. das scheint mir nicht richtig zu sein, da ich in dem Filter alles zugelassen habe. 

- In der Cytoscape Desktop visualisierung gibt es eine Relation "supports" von "Remote Function Call" nach "Functional Integration". "Remote Function Call" ist aber kein Anwendungssystem und "Functional Integration" keine Function. Folglich ist diese Relation falsch typisiert. Sie könnte evt. "increases" lauten. 

Gruß, AW

**Comment by KonradHoeffner** [comment]
Den Begriff gibt es auch nur einmal, es war ein Fehler in der Suche.
