### ISSUE TITLE
Submit Ticket für begriff

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#47]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser: Firefox

Wenn ich mit der linken Maustaste auf einen Knoten klicke und dann auf  "submit ticket" ziehe und loslasse, passiert nichts. Wenn ich es mit der rechten Maustaste mache, dann gehts. Es sollte entweder beides funktionieren oder bei der linken Maustaste erst gar nicht das Auswahlmenü angeboten werden. 

Grüße, AW

**Comment by KonradHoeffner** [comment]
Sollte mittlerweile funktionieren. Wenn nicht, bitte Ticket wieder öffnen.
