### ISSUE TITLE
Nutzung der rechten oder linken Maustaste

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#51]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser: Firefox 50 on Windows 7

wenn man mit der rechten Maustaste kurz einen Knoten anklickt, bekommt man das Auswahlmenü. Wenn man mit der linken Maustaste länger auf einen Knoten drückt, erscheint auch das Auswahlmenü und man kann auch etwas auswählen. Aber dann passiert nichts weiter. 
Vorschlag: Entweder passiert bei langanhaltendem Druck mit linker Maustaste gar nichts, oder aber nach Auswahl bekommt man auch die Funktion. 
Grüße, AW

**Comment by KonradHoeffner** [comment]
Das scheint ein Problem der Kontextmenübibliothek zu sein, habe [dort ein Ticket erstellt](https://github.com/cytoscape/cytoscape.js-cxtmenu/issues/56) und warte auf Antwort.

**Comment by KonradHoeffner** [comment]
Ich habe die Kontextmenübibliothek nochmal aktualisiert, geht es jetzt besser?

**Comment by KonradHoeffner** [comment]
Scheint jetzt zu gehen, bitte wieder aufmachen, wenn es nochmal auftritt.

**Comment by AlfredWinter** [comment]
Aktuell kann man das kontextmenü öffnen, wenn man die linke oder die rechte Maustaste lange drückt. Probleme:
- Wenn man bei langsamem Rechner einen Knoten verschieben will und laange links gedrückt hält, bis er sich dann endlich bewegt, geht oft vorher das Kontextmenü auf.
- üblicherweise geht ein Kontextmenü durch kurzen Rechtsklick auf und bleibt auch stehen. Die linke Maustaste ist für das Markieren(kurzes klicken) und das Bewegen (langes klicken) zustätndig.

Lösung: Kontextmeneü NUR mit kurzem Klick auf die rechte Maustaste öffnen.

**Comment by KonradHoeffner** [comment]
Um das Problem nachzustellen, wurden alle 8 CPUs auf 800 Mhz begrenzt (minimale Geschwindigkeit) via `sudo cpupower frequency-set -u 800Mhz` und der Firefox im 4k Vollbild genutzt, dann trat es sporadisch auf. Mit Python wurde dann noch eine Endlosschleife gestartet, um die Geschwindigkeit weiter zu reduzieren, dann erscheint das Problem häufiger.

Das Problem dabei, die Hauptmaustaste zu deaktivieren, ist, dass es dann bei mobilen Geräten ohne sekundäre Maustaste nicht mehr benutzbar ist.

Man müsste also eine Weiche einbauen, die je nach Eingabehardware (Maus vs Touchpad) das Menü unterschiedlich konfiguriert. Leider ist das unter JavaScript soweit ich weiß nicht ohne weiteres möglich. Allerdings kann man über den Browser oft herausfinden, ob es sich um ein mobiles Gerät handelt.

**Comment by AlfredWinter** [comment]
Bitte meinen Kommentar vom 22.10.2019 beachten!
Die Maustastenbelegung ist einfach nicht standardkonform! Das Kontextmenü darf nur mit der rechten Maustaste geöffnet werden. Die linke Maustaste ist für das Markieren von Objekten und bei langem Drücken für das Verschieben zuständig - und nicht für das Öffnen des Kontextmenüs

**Comment by KonradHoeffner** [comment]
So ist es in der neuen Version auch implementiert, ich aktualisiere das jetzt in der öffentlichen Version.
