### ISSUE TITLE
Anzeigen im Lod view

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#52]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser: firefox 50

bei bb wird im Lodview die subClass-Beziehung korrekt angezeigt. Sowohl wenn ein Knoten Subclass von einem anderen ist oder umgekehrt (inverse).
Bei CIOx wird es nicht angezeigt.

**Comment by KonradHoeffner** [comment]
Geht leider noch nicht, da Lodview über den SPARQL Endpunkt läuft.

**Comment by KonradHoeffner** [comment]
Da snik graph jetzt auch über den SPARQL Endpunkt läuft, müsste die Anzeige jetzt identisch sein.
