### ISSUE TITLE
Suche in CIOx geht nicht

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#53]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Suchen nach knoten aus CIOx geht nicht, z.B. "Sachkonto" - obwohl es da ist.

**Comment by KonradHoeffner** [comment]
Geht leider momentan nicht, da CIOX nicht im SPARQL Endpunkt öffentlich ist.

**Comment by KonradHoeffner** [comment]
Resolved by e7ec0f7bdb1b462142e128c357b4b917a643bd7f.
