### ISSUE TITLE
CIOx mal Deutsch, mal Englisch

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#54]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Die CIOx Knoten werden mal mit der Deutschen mal mit der Englischen Bezeichnung dargestellt.

**Comment by KonradHoeffner** [comment]
SNIK Graph bevorzugt englische Labels aber wenn diese nicht da sind, werden Deutsche benutzt, das ist daher ein Problem der CIOX Ontologie.
