### ISSUE TITLE
zwei Kürzeste Wege statt einem

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#56]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Obwohl ich mich über das ergebnis gefreut habe, ist es aber eigentlich falsch:
Ich wollte den kürzesten Weg von "Annual IT Budget" nach "Budget"(aus CIOx), habe aber einen Kreis bekommen.

**Comment by KonradHoeffner** [comment]
Mittlerweile scheint es zu funktionieren (siehe Bild), daher schließe ich das Ticket. Falls das Problem bei Ihnen doch noch auftritt, bitte wieder aufmachen, am besten mit Bild, damit ich das genaue Problem verstehe.

![budget](https://cloud.githubusercontent.com/assets/839577/24239567/ba50e0b8-0fae-11e7-9f2b-35e7cd4da455.png)
