### ISSUE TITLE
Ge"hide"ter Knoten kommt zurück

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#61]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
ich habe einen knoten in der Gesamtsicht gehidet und dann eine Pfadoperation gemacht. In dem neuen Fenster ist der Knoten auch nicht berücksichtigt. Wenn ich nun aber z.B. an einem der vorhandenen Knoten noch einen Star anfüge, taucht der gehidete Knoten wieder auf. 

Oder auch einfacher: Beispiel "bb-data" und "Research and Education Entity Type": Data und REET sind über eine kante verbunden. Wenn ich in der Ausgangsvisualisierung den REET ausblende und einen Star von data anfordere, dann taucht der REET trotzdem mit auf.
AW

**Comment by KonradHoeffner** [comment]
Ah, das kommt daher, dass ein Star vorher die Sicht zurücksetzt und bei "reset view" blende ich die entfernten Knoten wieder ein. Soll ich das umändern, sodass entfernte Knoten für die ganze Sitzung entfernt bleiben?

**Comment by KonradHoeffner** [comment]
Resolved in 9cd0a781bea672cbbe2420eb42817336aee99ba5.
