### ISSUE TITLE
hide geht erst beim 2. mal

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#62]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Situation: habe einen Star gemacht und mache weitere Stars dazu.
Wenn ich jetzt einzelne Knoten hiden will, geht das erst beim 2. Versuch.

**Comment by KonradHoeffner** [comment]
Ich kann den Fehler nicht replizieren, können Sie es nochmal probieren und wenn es wieder auftritt schreiben, welchen Browser, welche Browserversion und das genaue Vorgehen, bei dem Sie den Fehler bekommen haben (Stern bei welchen Knoten).

**Comment by KonradHoeffner** [comment]
Da die alte hide-Funktion nicht mehr existiert, schließe ich das mal.

**Comment by KonradHoeffner** [comment]
Die alte Hide-Funktion wurde entfernt in 4ce265945d43004acb260278baef33778a571a8c.
