### ISSUE TITLE
knoten lassen sich nur schwer greifen

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#63]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Im großen Ausgangsfenster genauso wie in den Fenstern nach einer Graphoperation:
Knoten lassen sich nur in ihrer oberen hälfte zum Verschieben greifen. Bei kleiner Vergrößerung ist das kaum möglich

**Comment by KonradHoeffner** [comment]
Der Mauscursor scheint fälschlicherweise mit dem Ende und nicht mit der Spitze auszulösen, denn man kann die Knoten auch ein Stück darüber bewegen. Merkwürdigerweise passiert das tatsächlich nur nach einer Graphoperation. Ich arbeite daran.
