### ISSUE TITLE
Anordnung der Knoten nach dem Auswählen von "Star"

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#69]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Wenn man zu einem Begriff die Funktion "Star" auswählt, sollte im Ergebnisbild der ausgewählte Begriff zusammen mit den über closeMatch verbundenen Knoten in der Mitte stehen, während alle anderen Begriffe in einem Kreis um dieses Zentrum angeordnet werden. Dies sollte entsprechend auch bei einem Sternchenwurm (auch doppelt) gemacht werden.

**Comment by AlfredWinter** [comment]
Die Knoten die um das Zentrum herumliegen, sollten nach Quelle sortiert sein.

**Comment by KonradHoeffner** [comment]
Das ist kein Problem, aber was soll passieren, wenn man einen Stern mit einem anderen Stern erweitert?

**Comment by AlfredWinter** [comment]
Dann bleibt der erste Stern wie er ist und um den neuen Mittelbpunkt wird ein neuer Kreis gezogen. Der Benutzer sollte dann das neue Zentrum zuerst soweit wie gewünscht aus dem alten Krreis herausrücken. 
 
ABER: Bei aller Begeisterung für diese schönen Funktionen liegt mir aber die direkte Bearbeitbarkeit der Ontologie für berechtigte User noch mehr am Herzen. Ich blicke dazu gebannt und ängstlich auf den Beginn Ihrer Elternzeit.
Grüße
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      ++49 341-97-16107, 
Mobile: ++49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Konrad Höffner [mailto:notifications@github.com] 
Gesendet: Mittwoch, 5. Juli 2017 15:17
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: AlfredWinter <alfred.winter@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Anordnung der Knoten nach dem Auswählen von "Star" (#69)
 
Das ist kein Problem, aber was soll passieren, wenn man einen Stern mit einem anderen Stern erweitert?

**Comment by KonradHoeffner** [comment]
OK habe es erstmal auf Meilenstein 0.6 vertagt nach dem Ontologieändern.

**Comment by KonradHoeffner** [comment]
Habe es als neue Operation "circle star" eingebaut, damit man immer noch den alten Star zur Verfügung hat, falls man doch mal die alte Funktionalität ohne Layoutänderung braucht. Ich mache die issue erstmal zu, bitte Bescheid sagen, falls es doch noch geändert werden soll.
