### ISSUE TITLE
farbe der bb-Knoten

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#70]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Warum sind die bb-Knoten nicht blau? War das nie?
AW

**Comment by KonradHoeffner** [comment]
Da habe ich einen Fehler bei der Farbkorrektur des Tagmodus gemacht. Im Code ist es auch schon korrigiert aber noch nicht im graph online.
