### ISSUE TITLE
download cytoscape graph

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#72]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:
Ist es möglich, beim Download des Cytoscape Graph nur den Teilgraphen herunterzuladen, den man gerade bearbeitet. D.h. wenn man z.B. eine Star-Operation ausgeführt hat, dass dann nur dieser Star heruntergeladen wird und das auch genau mit den Knotenpositionen, die man dort gerade festgelegt hat. 
Wäre schön. 
AW

**Comment by KonradHoeffner** [comment]
Das ist möglich über die Option File -> Save Visible Graph with Layout.

**Comment by AlfredWinter** [comment]
Das scheint dann aber nicht zu funktionieren. Es entsteht keine Cytoscape Datei, sondern "snikpart.json". AW

**Comment by KonradHoeffner** [comment]
Diese Datei kann man in Cytoscape laden über *Import* -> *Network* -> *File* (Hotkey [CTRL]+L).
Getested unter Cytoscape 3.4.0
