### ISSUE TITLE
Label für Kanten

### ISSUE THREAD

**Issue by BirgitSNIK** [IMISE/snik-cytoscape.js#90]
Auf den Kanten bitte nur das Label der Kante anzeigen, nicht die komplette Adresse.

**Comment by KonradHoeffner** [comment]
Behoben in commit aca7fcb39b7acd0957906d921a6db44d465a6ec0.

**Comment by AlfredWinter** [comment]
Es überlagern sich häufig mehrere Labels auf einer Kante. Da gibt es dann keinen Weg, etwas zu lesen. Ich weiß auch nicht, wie man das löst. Aber jetzt ist es ein Problem. AW

**Comment by KonradHoeffner** [comment]
Das ist ein ähnliches aber anderes Problem, das in Issue #143 behandelt wird. Ich suche nach einer Lösung.

**Comment by BirgitSNIK** [comment]
Mein Vorschlag:
wir können den Beziehungen eine Rangfolge zuordnen. Falls es zwischen zwei Begriffen mehr als eine Beziehung gibt (z.B. uses und updates), dann sollte nur die wichtigste angezeigt werden: im Beispiel "updates, ..". Die Punkte zeigen, dass es da noch mehr gibt. Geht man mit der Maus über die Beziehung, könnte ein kleines Fenster mit den übrigen Beziehungen aufpoppen. 

Keine Ahnung, wie leicht so etwas zu programmieren geht, ist zum Glück gerade auch nicht meine Aufgabe :-)!!!


Ich habe aber den Verdacht, dass hinter Mehrfachbeziehungen oft ein Fehler und gar kein echtes Wissen steckt: z.B. gleiche Beziehung in beiden Richtungen oder auch richtiger Mist. Aber laut Metamodell kann es durchaus Mehrfachbeziehungen zwischen zwei Begriffen geben.



Birgit



 Von:   AlfredWinter <notifications@github.com> 
 An:   IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com> 
 Kopie:   BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>, Author <author@noreply.github.com> 
 Gesendet:   05.12.2018 8:55 
 Betreff:   Re: [IMISE/snik-cytoscape.js] Label für Kanten (#90) 


Es überlagern sich häufig mehrere Labels auf einer Kante. Da gibt es dann keinen Weg, etwas zu lesen. Ich weiß auch nicht, wie man das löst. Aber jetzt ist es ein Problem. AW

**Comment by BirgitSNIK** [comment]
Was weglassen finde ich nicht gut. Alternativen:
·         Kanten kurvig machen oder
·         Doppelkante per Software entdecken und dann dynamisch beim Anzeigen ein zusammengesetztes Label anzeigen. 
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Birgit Schneider [mailto:birgit.schneider@imise.uni-leipzig.de] 
Gesendet: Mittwoch, 5. Dezember 2018 15:37
An: IMISE/snik-cytoscape.js <reply@reply.github.com>; Alfred Winter <alfred@imise.uni-leipzig.de>
Betreff: Re: [IMISE/snik-cytoscape.js] Label für Kanten (#90)
 
Mein Vorschlag:
wir können den Beziehungen eine Rangfolge zuordnen. Falls es zwischen zwei Begriffen mehr als eine Beziehung gibt (z.B. uses und updates), dann sollte nur die wichtigste angezeigt werden: im Beispiel "updates, ..". Die Punkte zeigen, dass es da noch mehr gibt. Geht man mit der Maus über die Beziehung, könnte ein kleines Fenster mit den übrigen Beziehungen aufpoppen. 
Keine Ahnung, wie leicht so etwas zu programmieren geht, ist zum Glück gerade auch nicht meine Aufgabe :-)!!!
 
Ich habe aber den Verdacht, dass hinter Mehrfachbeziehungen oft ein Fehler und gar kein echtes Wissen steckt: z.B. gleiche Beziehung in beiden Richtungen oder auch richtiger Mist. Aber laut Metamodell kann es durchaus Mehrfachbeziehungen zwischen zwei Begriffen geben.
 
Birgit
 
Von: AlfredWinter <notifications@github.com> 
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com> 
Kopie: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>, Author <author@noreply.github.com> 
Gesendet: 05.12.2018 8:55 
Betreff: Re: [IMISE/snik-cytoscape.js] Label für Kanten (#90) 
Es überlagern sich häufig mehrere Labels auf einer Kante. Da gibt es dann keinen Weg, etwas zu lesen. Ich weiß auch nicht, wie man das löst. Aber jetzt ist es ein Problem. AW

**Comment by KonradHoeffner** [comment]
Bitte in den Mails nur die Nachricht schreiben, sonst kommen die Signaturen, ursprünglichen Mails und so weiter in die Issue mit rein.

**Comment by KonradHoeffner** [comment]
Kanten kurvig machen ist möglich, allerdings fürchte ich um die jetzt schon suboptimale Performance. Gerade Kanten sind da wesentlich ressourcenschonender und wir zeigen ja zehntausende gleichzeitig an.

**Comment by AlfredWinter** [comment]
Und kurven nur dann, wenn es doppelte gibt?

**Comment by BirgitSNIK** [comment]
Den Vorschlag mit dem zusammengesetzten Label finde ich gut. Kurven kann ich mir nicht vorstelen.
Birgit
 
Von: Alfred Winter <alfred.winter@imise.uni-leipzig.de> 
Gesendet: Mittwoch, 5. Dezember 2018 15:58
An: 'Birgit Schneider' <birgit.schneider@imise.uni-leipzig.de>; 'IMISE/snik-cytoscape.js' <reply@reply.github.com>; 'Alfred Winter' <alfred@imise.uni-leipzig.de>
Betreff: AW: [IMISE/snik-cytoscape.js] Label für Kanten (#90)
 
Was weglassen finde ich nicht gut. Alternativen:
·         Kanten kurvig machen oder
·         Doppelkante per Software entdecken und dann dynamisch beim Anzeigen ein zusammengesetztes Label anzeigen. 
AW
 
 
a-------------´v-----------------------------p
Universität Leipzig KöR
Medizinische Fakultät
Institut für Medizinische Informatik, Statistik und Epidemiologie
Härtelstraße 16-18
D-04107 Leipzig

Prof. Dr. Alfred Winter
Tel.:      +49 341-97-16107, 
Mobil: +49 1515 5019248
E-Mail: alfred.winter@imise.uni-leipzig.de 
web: www.imise.uni-leipzig.de, www.3lgm2.de
facebook: www.facebook.com/medinfo.unileipzig 
 
Rektorin der Universität Prof. Dr. med. Beate A. Schücking, Ritterstraße 26, 04109 Leipzig 
Zuständige Aufsichtsbehörde: Sächsisches Staatsministerium für Wissenschaft und Kunst, Wigardstraße 17, 01097 Dresden, www.smwk.sachsen.de
 
Von: Birgit Schneider [mailto:birgit.schneider@imise.uni-leipzig.de] 
Gesendet: Mittwoch, 5. Dezember 2018 15:37
An: IMISE/snik-cytoscape.js <reply@reply.github.com>; Alfred Winter <alfred@imise.uni-leipzig.de>
Betreff: Re: [IMISE/snik-cytoscape.js] Label für Kanten (#90)
 
Mein Vorschlag:
wir können den Beziehungen eine Rangfolge zuordnen. Falls es zwischen zwei Begriffen mehr als eine Beziehung gibt (z.B. uses und updates), dann sollte nur die wichtigste angezeigt werden: im Beispiel "updates, ..". Die Punkte zeigen, dass es da noch mehr gibt. Geht man mit der Maus über die Beziehung, könnte ein kleines Fenster mit den übrigen Beziehungen aufpoppen. 
Keine Ahnung, wie leicht so etwas zu programmieren geht, ist zum Glück gerade auch nicht meine Aufgabe :-)!!!
 
Ich habe aber den Verdacht, dass hinter Mehrfachbeziehungen oft ein Fehler und gar kein echtes Wissen steckt: z.B. gleiche Beziehung in beiden Richtungen oder auch richtiger Mist. Aber laut Metamodell kann es durchaus Mehrfachbeziehungen zwischen zwei Begriffen geben.
 
Birgit
 
Von: AlfredWinter <notifications@github.com> 
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com> 
Kopie: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>, Author <author@noreply.github.com> 
Gesendet: 05.12.2018 8:55 
Betreff: Re: [IMISE/snik-cytoscape.js] Label für Kanten (#90) 
Es überlagern sich häufig mehrere Labels auf einer Kante. Da gibt es dann keinen Weg, etwas zu lesen. Ich weiß auch nicht, wie man das löst. Aber jetzt ist es ein Problem. AW

**Comment by BirgitSNIK** [comment]
Ok, wenn die Kurven nur  Bögen sind, dann bin ich einverstanden. Ich hatte an S-Kurven gedacht und eine Portion Spaghetti vor Augen! Birgit
 
Von: AlfredWinter <notifications@github.com> 
Gesendet: Mittwoch, 5. Dezember 2018 17:05
An: IMISE/snik-cytoscape.js <snik-cytoscape.js@noreply.github.com>
Cc: BirgitSNIK <birgit.schneider@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [IMISE/snik-cytoscape.js] Label für Kanten (#90)
 
Und kurven nur dann, wenn es doppelte gibt?
