### ISSUE TITLE
Filter funktionert in Star nicht.

### ISSUE THREAD

**Issue by AlfredWinter** [IMISE/snik-cytoscape.js#91]
*Please provide your browser name, version and operating system ([WhatIsMyBrowser.com](https://www.whatismybrowser.com/)).*
Browser:

**Comment by KonradHoeffner** [comment]
Filters work now in star mode but deactivating the filter brings back nodes outside of the star, which is not intended. I am investigating this. Probably related to issue #98.

**Comment by KonradHoeffner** [comment]
Should be fixed now through commit be5c0c402d828c42c71dd4b4501f9f837a015942.
