### ISSUE TITLE
Spiderworm function doesn't work (anymore)

### ISSUE THREAD

**Issue by vandenbergla** [IMISE/snik-cytoscape.js#92]
Browser: Chrome 67 on Windows 7

Few weeks back I was happy to find out that the Spiderworm function in the 'circle' worked. This is truly a handy feature. However, when I click on it now nothing happens. I would love to see this function return, as we want to include this functionality in our course assignments (Dept. Medical Informatics, University of Amsterdam).

**Comment by KonradHoeffner** [comment]
I can't replicate the problem, did you select a source node first? If yes and the problem persists, can you describe, between which nodes it didn't work?

**Comment by KonradHoeffner** [comment]
After a rework of graph.js, I still cannot replicate the problem. I am closing this for now, please comment if the problem persists.
