### ISSUE TITLE
Filter function not user friendly 

### ISSUE THREAD

**Issue by vandenbergla** [IMISE/snik-cytoscape.js#93]
Browser: Chrome 67 on Windows 7

Whenever I deselect something in the filter menu, the drop down menu closes. If I only want to showcase blue book (bb) concepts then I need to open the menu 14 times to deselect all the other options. Could this potentially be made a bit more user friendly? 

Kind regards,

Liesbeth 
(Dept. Medical Informatics, University of Amsterdam)

**Comment by KonradHoeffner** [comment]
You are right that is terrible usability. The menus don't automatically close now if you select an option in them but have to be closed explicitly by clicking on them.
