### ISSUE TITLE
German terms in graph

### ISSUE THREAD

**Issue by vandenbergla** [IMISE/snik-cytoscape.js#96]
Browser: Chrome 67 on Windows 7

There are quite some German definitions in the visualization even though it's supposedly derived from an English book. For example, if I search for: bb/tactical information management the graph reads: taktisches informationsmanagement and when I click on description in the 'circle' it shows the English definition. I can sort of figure out that taktisches informationsmanagement means tactical information management, but for terms such as: anwendungsbaustein, krankenhausverwaltung, etc. I need Google translate. I really hope it is possible to uniformly use the English definitions (or at least as an option) in this visualization, because now I cannot utilise it fully.

Kind regards,

Liesbeth
Dept. Medical Informatics, University of Amsterdam

**Comment by KonradHoeffner** [comment]
Hello Liesbeth,

All classes with the bb prefix are indeed derived from an English book. The problem occurs when both the English and the German label are present, as the German language is prioritized at the moment both in the graph and in the LodView RDF browser.

I will ask Prof. Winter if that is the intended behaviour or if English should be prioritized. However then the German students would get that problem with the German books.

In the LodView RDF browser, you can view a different language for [bb:TacticalInformationManagement](http://www.snik.eu/ontology/bb/TacticalInformationManagement) by clicking on the "EN" link. There seems to be no option to save the language preference, however. As it is not developed by us, only adapted, we cannot add such an option but I asked the developers at https://github.com/dvcama/LodView/issues/34.

In this SNIK Graph visualization, the priority is specified in style.js, I may tie this to a language option in the menu.

**Comment by KonradHoeffner** [comment]
Strange, English is already preferred:

            if(ele.data('le')&&ele.data('le')[0]) {label = ele.data('le')[0];}
            else if(ele.data('ld')&&ele.data('ld')[0]) {label = ele.data('ld')[0];}

It seems as if SNIK Graph does not load the English label, although the SPARQL query `select ?l {bb:TacticalInformationManagement rdfs:label ?l}` returns both an English and a German one. Maybe the SPARQL endpoint limit is set higher than the maximum and triples are missing?

**Comment by KonradHoeffner** [comment]
`group_concat(distinct(concat(?l,"@",lang(?l)));separator="|") as ?l ` is much faster, just have to split, sort and choose afterwards.
